### ISSUE TITLE
Not working at all in Chrome

### ISSUE THREAD

**Issue by aaron-wti** [tinymce/tinymce-angular#1]
When following the instructions in the README, I get the following error in the browser console:

> Uncaught TypeError: _this.onChangeCallback is not a function
>     at eval (tinymce-angular.es5.js:387)
>     at ZoneDelegate.invoke (zone.js:388)
>     at Object.onInvoke (core.js:4733)
>     at ZoneDelegate.invoke (zone.js:387)
>     at Zone.run (zone.js:138)
>     at NgZone.run (core.js:4550)
>     at yb.eval (tinymce-angular.es5.js:387)
>     at zd.r.fire (tinymce.min.js:2)
>     at yb.fire (tinymce.min.js:2)
>     at jy (tinymce.min.js:2)

Googling the error just shows that someone else experienced the same issue 3 days ago:
[https://community.tinymce.com/communityQuestion?id=9066100000097amAAA](https://community.tinymce.com/communityQuestion?id=9066100000097amAAA)

And there are no responses to that entry.

**Comment by fyrkant** [comment]
That's weird! I'll look into this tomorrow.

**Comment by aaron-wti** [comment]
Thanks!

**Comment by fyrkant** [comment]
@aaron-wti Can you give me more information on how you are using the editor component, maybe setup a simple repo that I can check out?

**Comment by fyrkant** [comment]
Ah, never mind, I think I found what the problem is, I'll have a new version out today

**Comment by fyrkant** [comment]
Can you try version 1.0.3 and see if it works any better?

**Comment by aaron-wti** [comment]
It works! The error is gone.

I also may have made a mistake in my code, I was doing this:
<```
editor
	[init]="{}"
	[inline]="true"
	[plugins]="['advlist autolink lists link image charmap print preview anchor searchreplace visualblocks code fullscreen insertdatetime media table contextmenu paste']"
	[toolbar]="'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image'"
	(change)="onChange($event)"
	[initialValue]="text"
></editor>
<div>{{text}}</div>
```

From reading this:
> tagName: Only used if the editor is inline, decides what element to initialize the editor on, defaults to div.

But I guess that isn't the correct way to do it?

I changed it to use "initialValue" instead so it is working now.

Thanks for the quick response!

**Comment by fyrkant** [comment]
Yeah, set the initial value with the `[initialValue]` prop.

**Comment by dev9-opine** [comment]
@fyrkant can you please help me to integrate plugin into tinymce-angular i have lots RnD but its not work, i want to integrate Latex plugin for creating math formulas into tinyMCE so is there any way?
i have refer [https://latex.codecogs.com/eqneditor/integration/tinymce_v4/install.php](url) this solution but i cant understand.
thanks in advance
