### ISSUE TITLE
RTL Direction doesn't work on tinymce-angular

### ISSUE THREAD

**Issue by ali-hasani** [tinymce/tinymce-angular#100]
According to the documentation of tinymce, to have rtl theme by default, we should have 'directionality: true' in the config, but it doesn't work in tinymce-angular.

**Comment by SimonFc** [comment]
Where do you read about setting `directionality` to boolean? [Here](https://www.tiny.cloud/docs/configure/localization/#directionality) the only valid options are strings, like [this](https://codesandbox.io/s/tinymceangular-ofl88?fontsize=14)

**Comment by ali-hasani** [comment]
absolutely [where](https://www.tiny.cloud/docs/configure/localization/#directionality) you said.
I don't know how, but it's now ok. I just made some changes in configuration.
Thank you anyway.

**Comment by SimonFc** [comment]
Ah okay, but great that it's working now!
