### ISSUE TITLE
How to upload images with angular and firebase

### ISSUE THREAD

**Issue by LuisSarmientoM** [tinymce/tinymce-angular#102]
### I want to implement the upload of images to firebase and then show them in tinyemce

-  in my component i have this:
 ![image](https://user-images.githubusercontent.com/42702720/62901694-137d6200-bd23-11e9-877e-454e4330a046.png)

- in images_upload_handler I save the image in the storage using the service like this:
 ![image](https://user-images.githubusercontent.com/42702720/62901909-9acad580-bd23-11e9-81b4-12e7c16b2398.png)

With this, the images are correctly saved in the storage but are not shown in the editor.

**Any recommendations or guides to help me?**

**Comment by SimonFc** [comment]
Have you tried using the success callback with the URL as described [here](https://www.tiny.cloud/docs/configure/file-image-upload/#images_upload_handler)?

I'll close this as it isn't an issue but let me know if you got any questions.
