### ISSUE TITLE
Tinymce issue with prod build in angular. Any fix for it ??

### ISSUE THREAD

**Issue by rohit7692** [tinymce/tinymce-angular#103]
![image](https://user-images.githubusercontent.com/45750829/63185090-b06b3280-c076-11e9-971c-9fbd44ed4448.png)

**Comment by SimonFc** [comment]
What build-options do you use when building? And what version of Angular do you use?

**Comment by lnewson** [comment]
It'd also be useful if you can provide a package.json or lock file so we can see what versions you are using, as that error is from Angular trying to compile/process tslib, which isn't related to TinyMCE. So it's possible there's an issue with your TypeScript version, or something similar to that.

**Comment by rohit7692** [comment]
![image](https://user-images.githubusercontent.com/45750829/63224363-98172700-c1e0-11e9-905d-bc3cbb936136.png)
[package.zip](https://github.com/tinymce/tinymce-angular/files/3513006/package.zip)

@SimonFc  building application with command 'ng build --prod'.or version details I have attached the details
@lnewson I have attached the package.json and version details

**Comment by SimonFc** [comment]
Yeah what lnewson says.
Install the packages defined by your package file and read through the warnings you get for mismatched peer-dependencies. (You can ignore the miss-match of the angular dependencies for tinymce-angular, we're probably going to change that on our side)

Try installing typescript@~2.6.0 (for @angular/compiler-cli) as the version you specify now will resolve to 2.9.2

**Comment by rohit7692** [comment]
Thnx @SimonFc  after changing the typescript version to ~2.6.0 it's working

**Comment by SimonFc** [comment]
Great! I'll close this then
