### ISSUE TITLE
tinyMCE not working on mat-tab-group

### ISSUE THREAD

**Issue by leomayer** [tinymce/tinymce-angular#105]
I place tinymce on a `mat-tab-group` like written on [Stackoverflow](https://stackoverflow.com/q/56985764/325868). After switching the first time the tabs the content isn't any longer editable nor displayed at all.

Looking for solutions I didn't find any. Especially since the solutions are already aged or simply don't work. I see it as lack of documentation how to use them properly together with Material.

Using: Angular 8, tinyme-angular: 3.2.0

**Comment by SimonFc** [comment]
There are some known issues when using tinymce-angular with tabs due to the usage of an iframe by TinyMCE. There's a [Storybook example](https://github.com/tinymce/tinymce-angular/tree/master/stories/materialtabs) which illustrates one possible workaround of the issue. Let me know if you got any questions!

**Comment by leomayer** [comment]
Following the Storybook I have several problems with the sample:

1. Don't know what `<editor-count></editor-count>` should refer to. I guess its not crucial there I dropped it.
2. Following directly the sample I get an Angular-Error about expression changed after init. To fix it I change the sample to :

```
constructor(private cd: ChangeDetectorRef, ) {}
...
  public ngAfterViewInit() {
    this.activeTabIndex = this.tabGroup.selectedIndex;
    this.cd.detectChanges();
  }
```

3. The major problem I have with the sample is that the editor opens fine at the first Tab, but on the second it fails...  I get the following error

```ERROR TypeError: Cannot read property 'open' of undefined
    at Object.initContentBody (tinymce.js:24263)
    at Object.init$1 [as init] (tinymce.js:24433)
    at Object.init$2 [as init] (tinymce.js:24569)
    at Editor.<anonymous> (tinymce.js:24683)
    at Array.<anonymous> (tinymce.js:7274)
    at each$1 (tinymce.js:2113)
    at loadScripts (tinymce.js:7271)
    at ScriptLoader.loadScripts (tinymce.js:7284)
    at ScriptLoader.loadQueue (tinymce.js:7220)
    at tinymce.js:24681
```

After some testing I figured out that the problem relates to the second tab, i.e. I cannot display second. Seems like the very first remains somehow...
Any ideas how to fix?

**Comment by SimonFc** [comment]
Yeah you can ignore the editor-count component, it's just a helper to display the number of active editors.

Is your version exactly the same as the Storybook example? I just opened it up and I don't get any errors when switching tabs :thinking:

**Comment by leomayer** [comment]
Well... The Error is only when initiating the component... Some kind of debug-error that the expression has been changed after .... 
no error afterwards.

If I look in your example of #76 than you provide a link with a [workaround](https://stackblitz.com/edit/angular-9uvqzk?file=src%2Fapp%2Fapp.component.ts). There the `detectChanges()` is included as well...  Altough there it works as well without...

I think it won't harm to have an additional check therein...

**Comment by SimonFc** [comment]
Yeah that was an initial workaround that I came up with, and the Storybook example is a simpler one. If there's an issue with it I would like to know what it could be but I can't reproduce it :thinking:

**Comment by joelkesler** [comment]
You can also try lazy-loading the mat-tab content. That worked for me when dealing with this issue:

```html
<mat-tab-group #tabGroup (selectedTabChange)="handleTabChange($event)">
  <mat-tab label="First Tab">
    <ng-template matTabContent>
      <editor [apiKey]="apiKey" [(ngModel)]="firstEditorValue"></editor>
    </ng-template>
  </mat-tab>

  <mat-tab label="Second Tab">
    <ng-template matTabContent>
      <editor [apiKey]="apiKey" [(ngModel)]="secondEditorValue"></editor>
    </ng-template>
  </mat-tab>
</mat-tab-group>
```

Docs: https://material.angular.io/components/tabs/overview#lazy-loading

**Comment by msbhavana** [comment]
None of the above workarounds are viable for me. Any other fix/plan to fix has been made ?
