### ISSUE TITLE
Can we integration (@wiris/mathtype-tinymce4) package ?

### ISSUE THREAD

**Issue by Asifislam110** [tinymce/tinymce-angular#107]
I am using following configuration in angular template.but not displaying (chem,formula) icons.

<editor apiKey="{{key}}" [init]="{
    external_plugins: {
        'tiny_mce_wiris' : '{{ServerPath}}/mathtype-tinymce4/plugin.min.js'
    },
    toolbar: 'tiny_mce_wiris_formulaEditor,tiny_mce_wiris_formulaEditorChemistry'
  }"></editor>

**Comment by SimonFc** [comment]
It looks like it should work. Do you get any errors?
