### ISSUE TITLE
Save plugin refreshes entire page 

### ISSUE THREAD

**Issue by shogan94** [tinymce/tinymce-angular#108]
When wrapped in a form component and using the save plugin, the page always reloads on save. Occasionally the submit function will be called right before but not always. Is it possible to use the save plugin and not refresh/reload the entire page, and instead just 'submit'? 

Heres a small sandbox.... [codesandbox](https://codesandbox.io/embed/tinymceangular-5thjg)

I'm expecting the submit function to be called and the page not to be reloaded unless said to. 

TinyMCE/TinyMCE-Angular: v3.3.0
TinyMCE: v.5.0.14

**Comment by SimonFc** [comment]
If you add an (save_callback)[https://www.tiny.cloud/docs/plugins/save/#save_onsavecallback] you're able to take over the action. [Example](https://codesandbox.io/s/tinymceangular-m391e?fontsize=14) Let me know if you got any questions!
