### ISSUE TITLE
The listener callback is very slow

### ISSUE THREAD

**Issue by CodeFronts** [tinymce/tinymce-angular#110]
**What is the current behavior? Describe the bug**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by SimonFc** [comment]
I don't seem to have this issue here: [example](https://codesandbox.io/s/tinymceangular-mut9n?fontsize=14) See if you can reproduce the issue you have

**Comment by randallmeeker** [comment]
I came into this issue after experiencing the same thing. I would get (onChange) updates when adding text to the editor, but I would not get these updates when deleting (backspace or delete key). Then when I unfocused, I would get  a delayed change event. 

Here is a [CodeSandbox](https://codesandbox.io/s/tinymceangular-4vm90)

If you start editing you will see console updates. If you hit delete, you will not see these updates. Then you will occasionally see a delayed update on blur.

**Comment by virendrasinghpawar** [comment]
facing similar issue in tiny mce angular version any update on this

**Comment by jscasca** [comment]
Hi @randallmeeker @virendrasinghpawar 

If you are using the `onChange` event handler you have to keep in mind that it will trigger when the element has finished changing.
> change event is not necessarily fired for each alteration to an element's value
You can copy Simon's code and subscribe to the form's valueChange or use the NgModel directive instead. Let me know if this helps or if you have a different replication. In the meantime I will be closing this ticket.

Cheers,
