### ISSUE TITLE
model doesn't get updated when ChangeDetection = onPush 

### ISSUE THREAD

**Issue by andreash92** [tinymce/tinymce-angular#112]
**What is the current behavior?**
 Model doesn't get updated when ChangeDetection = onPush 
![image](https://user-images.githubusercontent.com/16178577/65028786-4b408080-d945-11e9-8f20-32cb095d55cd.png)
Model and Validators are not getting updated after I write something 

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6zlmmkkk1n?fontsize=14) or similar.**

- Use ReactiveForms
- Set ChangeDetection to OnPush 
- (optional) set Required validator  
- Update the model from UI. The FormControl doesn't get updated 

**What is the expected behavior?**

 Update model (value and validators) while typing when ChangeDetection = OnPush

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or TinyMCE-Angular?**

 - Im using Angular 8.2.0 and TinyMCE 3.3.0

**Comment by SimonFc** [comment]
Hi @andreash92, would you be able to set up a reproduction of this issue on CodeSandbox?

**Comment by andreash92** [comment]
after upgrading both tinymce and tinymce-angular to 5.0.15 and 3.3.0 respectively, i don't have this behaviour anymore.
