### ISSUE TITLE
base_url seems to do nothing 

### ISSUE THREAD

**Issue by andreash92** [tinymce/tinymce-angular#113]
**What is the current behavior?**
this is my editor: 
```
<editor   [init]="{
    base_url: '/tinymce', 
      suffix: '.min',       
      menubar: false,
      branding: false,
      statusbar: false,
      plugins: 'lists, textcolor' 
    }"  [(ngModel)]="value"  [inline]="true" [disabled]="isDisabled"></editor>
```
but i get the follow errors 
![image](https://user-images.githubusercontent.com/16178577/65137058-58c33c80-da11-11e9-9fc1-b565020fee32.png)

it seems that base_url is not applied at all!

**Comment by SimonFc** [comment]
What version of TinyMCE are you using? The `base_url` and `suffix` options were added in ver. 5.0.8

**Comment by andreash92** [comment]
I was using tinymce 4.8. 
I run `yarn add @tinymce/tinymce-angular@latest` and i thought that i will get the latest tinymce also. 
After yarn `add tinymce@latest` , base_url works as expected

**Comment by pwilkowski** [comment]
This is still not working, I have tinymce 5.1.6 and tinymce looks for their resources in `/` directory so it completely skips base_url

workaround is to change this in angular.json

```
{ "glob": "**/*", "input": "node_modules/tinymce/skins", "output": "/tinymce/skins/" },
{ "glob": "**/*", "input": "node_modules/tinymce/themes", "output": "/tinymce/themes/" },
{ "glob": "**/*", "input": "node_modules/tinymce/plugins", "output": "/tinymce/plugins/" }```
to this:
```
{ "glob": "**/*", "input": "node_modules/tinymce/skins", "output": "/skins/" },
{ "glob": "**/*", "input": "node_modules/tinymce/themes", "output": "/themes/" },
{ "glob": "**/*", "input": "node_modules/tinymce/plugins", "output": "/plugins/" }
```
Original solution was found here:
https://stackoverflow.com/a/57419965/325606
