### ISSUE TITLE
How can I load an external plugin?

### ISSUE THREAD

**Issue by yunseok** [tinymce/tinymce-angular#114]
I'm trying to load `tinymce-mention` but it says it is not found in the console

**Comment by SimonFc** [comment]
Hi @yunseok, do you have an example of your current configuration? We have some documentation on usage of external_plugins over [here](https://www.tiny.cloud/docs/configure/integration-and-setup/#external_plugins)

**Comment by jscasca** [comment]
hi @yunseok 

Were you able to load the external plugin? Let me know if this is still an issue otherwise I will close this for inactivity
