### ISSUE TITLE
How use extended_valid_elements to angular component?

### ISSUE THREAD

**Issue by kbatyrbayev** [tinymce/tinymce-angular#118]
**How use extended_valid_elements to angular component?**

I tried like this
`tinymce.init({`
      `selector: '.page',`
      `inline: true,`
      `extended_valid_elements: "app-my-component",`
      `custom_elements: "app-my-component",`
   ` });`

**But tiny doesn't see it as a component**

What can be done?

**Comment by SimonFc** [comment]
You want to edit the DOM of your Angular Component with TinyMCE? You would break the mapping that Angular keeps to it by doing so. Your selector wouldn't be able to be on any element directly managed by Angular either(without breaking stuff). I'm curious about how it would work out though so I made a [CodeSandbox](https://codesandbox.io/s/tinymceangular-5tqkj?fontsize=14).

You could perhaps experiment some with the [noneditable](https://www.tiny.cloud/docs/plugins/noneditable/) plugin :thinking: 

I'm closing this as this isn't an issue with tinymce-angular, nor something we'll support.
