### ISSUE TITLE
Custom font(.woff) not working within the editor

### ISSUE THREAD

**Issue by Baelx** [tinymce/tinymce-angular#124]
**What is the current behavior?**
Custom font hosted locally which are loaded in to the editor seem to render into the font-select area but not in the editor body itself. Instead, it appears custom fonts revert to Times New Roman by default even if font-select indicates the custom font it being used.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6zlmmkkk1n?fontsize=14) or similar.**
- Create a new project with the angular cli and install tinymce and tinymce-angular. Add tinymce-angular's EditorModule within app.module.ts
- Create a fonts folder in your project and add your custom fonts
- Reference those fonts with a css @font-face declaration in the main styles.css file that comes packaged with your project.
- In the app component, add in the editor component and pass an init object to it declaring the fonts you'd like available to it(including your custom font(s))
- ng serve and view the app

**What is the expected behavior?**
The editor module should use the specified font for text within the editor body.

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or TinyMCE-Angular?**
Versions used:
- "tinymce": "^5.1.4",
- "@tinymce/tinymce-angular": "^3.3.1",
- Chrome:  79.0.3945.88 

**Screenshot**
![image](https://user-images.githubusercontent.com/16845197/71270929-a3ea3580-2307-11ea-9b5a-fe9d1bf8cb01.png)

**Comment by SimonFc** [comment]
Hi @Baelx,

When you're using TinyMCE in iframe mode you must make any css you wish your content to have available inside the iframe - you do this by using something we call content css. There're two options for this, the [content_css](https://www.tiny.cloud/docs/configure/content-appearance/#content_css) option and the [content_style](https://www.tiny.cloud/docs/configure/content-appearance/#content_style) option. If you add the same font-face declaration to your content css it should work alright. Let me know if this solves your problem!
