### ISSUE TITLE
Self hosting not working once deployed to production environment

### ISSUE THREAD

**Issue by critchie** [tinymce/tinymce-angular#129]
**What is the current behavior?**
I have followed all the steps from here:
https://www.tiny.cloud/docs/integrations/angular/#tinymceangularintegrationquickstartguide under the heading: TinyMCE Self-hosted.  I completed all four steps. When executing on my local machine tinymce.min.js comes from my local folders.  When I do a build for production ng build --prod and deploy the app to our server the tinymce.min.js is loaded from tiny.cloud despite all my settings. Because it is coming from tiny.cloud I get the no API Key warning.

**What is the expected behavior?**
When deployed tinymce.min.js would continue to download from my code base and not from tiny.cloud.

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or TinyMCE-Angular?**
tinymce: 5.1.5
@tinymce/tinymce-angular: 3.3.1 
angular: 8.2.13
Chrome: 79
Windows 10

**Comment by SimonFc** [comment]
Sounds like the tinymce.min.js script somehow isn't being included in your prod build or it's being loaded too late. Are you lazy-loading any modules?

Something you could try is to add `import 'tinymce';` in the module which tinymce-angular is being included in. If that solves the issue the issue is probably one related to your specific setup. If you share your angular.json configuration I could see if I see anything strange

**Comment by critchie** [comment]
The editor is being used in a lazy loaded module.

I also have a custom plugin that works fine in Dev but isn't found when deployed.  And if I put the `import 'tinymce'` in my lazy loaded module.ts and run it on my machine my custom plugin can't be found (in the browser DevTools network tab I see a 404 when my custom plugin is requested by the editor).  If I leave the `import 'tinymce'` out, my custom plugin works but I don't see in the browser DevTools network tab where it is loaded. It is all very strange.

angular.json is right out of the box except for my asset/script/style additions:

```
{
	"$schema": "./node_modules/@angular/cli/lib/config/schema.json",
	"version": 1,
	"newProjectRoot": "projects",
	"projects": {
		"admin-sessions": {
			"root": "",
			"sourceRoot": "src",
			"projectType": "application",
			"prefix": "kt",
			"schematics": {
				"@schematics/angular:component": {
					"style": "scss"
				}
			},
			"architect": {
				"build": {
					"builder": "@angular-devkit/build-angular:browser",
					"options": {
						"outputPath": "dist",
						"index": "src/index.html",
						"main": "src/main.ts",
						"polyfills": "src/polyfills.ts",
						"tsConfig": "src/tsconfig.app.json",
						"assets": [
							"src/favicon.png",
							"src/assets",
							"src/web.config",
							{
								"glob": "**/*",
								"input": "node_modules/tinymce/skins",
								"output": "/tinymce/skins/"
							},
							{
								"glob": "**/*",
								"input": "node_modules/tinymce/themes",
								"output": "/tinymce/themes/"
							},
							{
								"glob": "**/*",
								"input": "node_modules/tinymce/plugins",
								"output": "/tinymce/plugins/"
							},
							{
								"glob": "**/*",
								"input": "src/assets/plugins/tinymce",
								"output": "/tinymce/plugins/"
							}
						],
						"styles": [
							"node_modules/perfect-scrollbar/css/perfect-scrollbar.css",
							"node_modules/socicon/css/socicon.css",
							"node_modules/@fortawesome/fontawesome-free/css/all.min.css",
							"src/assets/plugins/line-awesome/css/line-awesome.css",
							"src/assets/plugins/flaticon/flaticon.css",
							"src/assets/plugins/flaticon2/flaticon.css",
							"src/assets/sass/style.angular.scss",
							"node_modules/ng-uikit-pro-standard/assets/scss/bootstrap/bootstrap.scss",
							"node_modules/ng-uikit-pro-standard/assets/scss/mdb.scss",
							"node_modules/animate.css/animate.css",
							"src/styles.scss"
						],
						"scripts": [
							"node_modules/popper.js/dist/umd/popper.js",
							"node_modules/tooltip.js/dist/umd/tooltip.min.js",
							"node_modules/perfect-scrollbar/dist/perfect-scrollbar.js",
							"node_modules/tinymce/tinymce.min.js",
							"src/assets/plugins/tinymce/properties-plugin.js"
						],
						"stylePreprocessorOptions": {
							"includePaths": [
								"src/assets"
							]
						},
						"es5BrowserSupport": true
					},
					"configurations": {
						"production": {
							"fileReplacements": [
								{
									"replace": "src/environments/environment.ts",
									"with": "src/environments/environment.prod.ts"
								}
							],
							"scripts": [],
							"optimization": true,
							"outputHashing": "all",
							"sourceMap": false,
							"extractCss": true,
							"namedChunks": false,
							"aot": true,
							"extractLicenses": true,
							"vendorChunk": false,
							"buildOptimizer": true,
							"budgets": [
								{
									"type": "initial",
									"maximumWarning": "5mb",
									"maximumError": "10mb"
								}
							]
						}
					}
				},
				"serve": {
					"builder": "@angular-devkit/build-angular:dev-server",
					"options": {
						"browserTarget": "admin-sessions:build",
						"host": "localdev"
					},
					"configurations": {
						"production": {
							"browserTarget": "admin-sessions:build:production"
						}
					}
				},
				"extract-i18n": {
					"builder": "@angular-devkit/build-angular:extract-i18n",
					"options": {
						"browserTarget": "admin-sessions:build"
					}
				},
				"test": {
					"builder": "@angular-devkit/build-angular:karma",
					"options": {
						"main": "src/test.ts",
						"polyfills": "src/polyfills.ts",
						"tsConfig": "src/tsconfig.spec.json",
						"karmaConfig": "src/karma.conf.js",
						"styles": [
							"src/styles.scss"
						],
						"scripts": [],
						"assets": [
							"src/assets"
						]
					}
				},
				"lint": {
					"builder": "@angular-devkit/build-angular:tslint",
					"options": {
						"tsConfig": [
							"src/tsconfig.app.json",
							"src/tsconfig.spec.json"
						],
						"exclude": [
							"**/node_modules/**"
						]
					}
				}
			}
		},
		"admin-sessions-e2e": {
			"root": "e2e/",
			"projectType": "application",
			"prefix": "",
			"architect": {
				"e2e": {
					"builder": "@angular-devkit/build-angular:protractor",
					"options": {
						"protractorConfig": "e2e/protractor.conf.js",
						"devServerTarget": "admin-sessions:serve"
					},
					"configurations": {
						"production": {
							"devServerTarget": "admin-sessions:serve:production"
						}
					}
				},
				"lint": {
					"builder": "@angular-devkit/build-angular:tslint",
					"options": {
						"tsConfig": "e2e/tsconfig.e2e.json",
						"exclude": [
							"**/node_modules/**"
						]
					}
				}
			}
		}
	},
	"defaultProject": "admin-sessions"
}
```

**Comment by SimonFc** [comment]
Hmm I don't see anything that's out of place. So if I understand you correctly, when you did `import 'tinymce';` it did not load from Cloud. That narrows it down slightly.

As a sanity check you could investigate the contents of your build output (dist) and check if you have a script there containing tinymce (just search for "tinymce", if you find a file with 20+ matches then that's it) and that it's actually being loaded in your index.html file.

As a second sanity check you could try to just remove tinymce-angular from your templates and check if you still get a global called tinymce when running your project (just log `window.tinymce`, and maybe `window.tinymce.baseURI` as well while you're at it)

As long as the main tinymce script is loaded before the tinymce-angular component mounts it should not fetch it from Tiny's cloud services.

I'm just brainstorming at this point but hopefully you'll be able to find what the issue.

**Comment by critchie** [comment]
Here is the dist folder from ng build --prod 
![image](https://user-images.githubusercontent.com/340046/72625262-74cee000-3916-11ea-8b62-8e36b98d604b.png)

In assets/plugins/tinymce you can see my custom plugin.  In this folder I don't see tinymce.min.js anywhere unless it is bundled.

When I run this locally here is what logging window.tinymce gives me:
![image](https://user-images.githubusercontent.com/340046/72625410-bf505c80-3916-11ea-9b7e-389b1349f2a6.png)

When I run it deployed I get this:
![image](https://user-images.githubusercontent.com/340046/72626393-a47ee780-3918-11ea-9233-e16f7102d4e0.png)

So it seems the tinymce.min.js is not being included in the build to production.  Or it is being bundled up such that it can't be found.

Here is one of my configs:
```
{
	height: "500",
	menubar: "file edit view insert format tools table help",
	menu: {
		insert: {
			title: "Insert",
			items:
				"image link media inserttable | charmap | anchor | insertdatetime | assessment participant program rater"
		}
        },
        contextmenu: "assessment participant program rater",
	base_url: "/tinymce",
	suffix: ".min",
	plugins: [
		"advlist autolink lists link image charmap print preview anchor",
		"searchreplace visualblocks code fullscreen",
		"insertdatetime media table paste code help properties"
	],
	toolbar:
		"undo redo | formatselect | properties | bold italic backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help"
}
```

**Comment by SimonFc** [comment]
I have been thinking about it for a bit but can't see what the issue could be.

What you could to if you don't manage to find the problem is to just keep the `import 'tinymce';` and add your "properties-plugin.js" to your assets property in your angular.json. You can then load it using the [external_plugins](https://www.tiny.cloud/docs/configure/integration-and-setup/#external_plugins) setting.

I think the reason you got a 404 earlier with your custom plugin is because you loaded it as a global script and it got executed before before the main tinymce.js script had been run. Not loading it as a global script and using the external_plugins setting should fix that

I'll close since this isn't an issue with tinymce-angular nor TinyMCE

**Comment by critchie** [comment]
So the final solution was to follow the four steps in the instructions as stated in my OP.
Then:
1. Add `import "tinymce";` in the module.ts file of my lazy loaded module.
2. Add
```
external_plugins: {
	properties: "plugins/properties-plugin.js"
}
```
to the editor init to get the custom plugin to load.

My angular.json file posted earlier didn't change and in particular ensure the custom plugin gets included in your build:
```
{
	"glob": "**/*",
	"input": "src/assets/plugins/tinymce",
	"output": "/tinymce/plugins/"
}
```

Hope this helps someone in the future.
