### ISSUE TITLE
WARNING: Too many active WebGL contexts. Oldest context will be lost.

### ISSUE THREAD

**Issue by rcadhikari** [tinymce/tinymce-angular#13]
We started using a trial version of TinyMce on our developing app. And we have a situation where we would need use the editor multiple times (20-30 times) in a single page, in fact its a single form having multiple textarea fields. 

It all looks good however we get the warning on javascript console saying:

"WARNING: Too many active WebGL contexts. Oldest context will be lost.".

Any help would be really appreciated.

**Comment by MichaelFromin** [comment]
What browser are you using when this happens?  What code are you using to initialize TinyMCE?  If you are on a free trial of TinyMCE Cloud you should open a support ticket at http://support.ephox.com and we can provide you assistance via that mechanism.

**Comment by fyrkant** [comment]
This has been fixed.
