### ISSUE TITLE
add focus function on editor

### ISSUE THREAD

**Issue by keatkeat87** [tinymce/tinymce-angular#130]
I think EditorComponent should have a focus method.
then we can use it when error or initial.

**Comment by SimonFc** [comment]
Like this?
`<editor (onFocus)="handleEvent($event)"></editor>`
[Event binding](https://www.tiny.cloud/docs/integrations/angular/#eventbinding)

**Comment by keatkeat87** [comment]
no, i mean 
```
<button (click)="editor.focus()" >click</button>
<editor #editor ></editor>
```

**Comment by SimonFc** [comment]
(Looks like I updated my response just when you replied) Is the focus method on the editor what you're looking for?

**Comment by keatkeat87** [comment]
yes. that's what i need. 

currently,  i can do like that
```
<button (click)="editor.editor.focus()" >click</button>
<editor #editor ></editor>
```
but I think direct use the internal editor instance is not good.

1 more thing to highlight, when we call tinymceEditor.focus(), the browser won't scroll to the textarea
maybe it is tinymceEditor problem, but we can also let focus on tinymce-angular component host first and then focus to inside, it will trigger browser scroll.

**Comment by SimonFc** [comment]
tinymce-angular is just a wrapper around TinyMCE which happens to be mapping a small subset of the most commonly used APIs for convenience. The APIs documented for [TinyMCE](https://www.tiny.cloud/docs/) are intended to be used when using tinymce-angular as well.

For the scrolling part, what you can is to call `editor.getContainer().scrollIntoView()` or maybe `editor.getBody().scrollIntoView()` if you're using inline mode. Does this work for you?

**Comment by keatkeat87** [comment]
ok, i got it.
thank you for your information
