### ISSUE TITLE
Scrollbars for Editor

### ISSUE THREAD

**Issue by leomayer** [tinymce/tinymce-angular#131]
**What is the current behavior?**

In our current layout the tinyMCE is placed on a Material tab and there with further restrictions. The display works quite well and the editor is placed quite properly. The problem is that the editor has vertical scrollbars which I want to get rid of.

I figured out that if I set on `iframe->#document->html` the following CSS:

```
overflow: hidden
overflow-x: auto
```

the scrollbars work as expected. I have no clue how to set in the `editor` or in the styles. I found that I could set `body_class` but this seems a different issue since the `iframe` is encapsulated. Is there a different way to achieve the result?

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or TinyMCE-Angular?**

using 

```
@tinymce/tinymce-angular": "^3.3.1"
"tinymce": "^5.1.5",
```

**Comment by SimonFc** [comment]
@leomayer So the CSS need to be in the iframe as you already have discovered. There're two options for this, [content_style](https://www.tiny.cloud/docs/configure/content-appearance/#content_style) and [content_css](https://www.tiny.cloud/docs/configure/content-appearance/#content_css). They're intended for providing styles for the content when in iframe mode but will work for your use case as well.

[Example](http://fiddle.tinymce.com/LZgaab) with vanilla TinyMCE.
