### ISSUE TITLE
Noneditable and annotations

### ISSUE THREAD

**Issue by leomayer** [tinymce/tinymce-angular#133]
**What is the current behavior?**

I need a readonly version of `tinyMCE` with content which has annotations. On the annotations I have the problem with the selections since the events are occuring twice.

I am aware that I need 

- `editor.getBody().setAttribute('contenteditable', false); `
- the plugin `noneditable`
- `noneditable_noneditable_class = 'mce-annotation';`

I have an open issue with the tinyMCE support. My sample is given at

https://codepen.io/leomayer/pen/zYxbYMj?editors=1111

I am aware that adding **new** annotations causes the problem that the console is triggered twice when clicking on an annotation while only once when clicking on an existing.

When I try to load the content into the `editor` the annotation still fires two events although the given JS code works fine. I used

```
<editor [init]="editMceSettings" [ngModelOptions]="{standalone: true}" [(ngModel)]="data.edit.content">
</editor>
```

I would guess that the content is loaded from the ngModel AFTER the plugin has already evaluated the conent. But I'm not sure. At least for the given sample I would like to have the same behaviour as in JS.

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or TinyMCE-Angular?**

tinyMCE: 5.1.5, tinymce-angular: 3.3.1

**Comment by SimonFc** [comment]
Closing this since the issue was resolved via the TinyMCE support.
