### ISSUE TITLE
Support for Angular 9

### ISSUE THREAD

**Issue by Jahrenski** [tinymce/tinymce-angular#135]
In order to suppress warnings and guarantee support, we should update the Angular dependencies to Angular 9 as is has been fully released.

Warnings: 

`
npm WARN @tinymce/tinymce-angular@3.4.0 requires a peer of @angular/core@>=5.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @tinymce/tinymce-angular@3.4.0 requires a peer of @angular/common@>=5.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @tinymce/tinymce-angular@3.4.0 requires a peer of @angular/forms@>=5.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.
`

**Comment by magnusbakken** [comment]
I was just about to create this issue myself. According to my testing the current version of tinymce-angular seems to be working fine with Angular 9, without any code changes, but so far I have only tested with enableIvy=false.

**Comment by Jahrenski** [comment]
I noticed the same and i'm using Ivy ;)

**Comment by SimonFc** [comment]
We (the maintainers) are currently investigating what approach to take when it comes to supporting different versions of Angular. I have yet to run the test suite with Angular 9 but on the surface there doesn't seem to be any change made to Angular 9 which would affect tinymce-angular. We'll update this issue once we have a new version published

**Comment by timrasche** [comment]
+1, ivy enabled, seems to be working as expected.

**Comment by Jahrenski** [comment]
Still debugging but there seems to be an interaction issue with Ionic 5 / Angular 9 with Tiny's editor on iOS only. If the editor has the focus, you are unable to scroll without dismissing the keyboard.

**Comment by Jahrenski** [comment]
Here's a minimum reproduction of the issue and link to my Ionic's Issue:

[Stackblitz Ionic-v5-TinyMCE](https://stackblitz.com/edit/ionic-v5-tinymce)
[Ionic Issue](https://github.com/ionic-team/ionic/issues/20672)

**Comment by mtpultz** [comment]
Is it possible to cut a npm build for v9?  Seems to be working

**Comment by the-super-coder** [comment]
I know covid-19 is causing the development slow everywhere, however, how soon are we expecting a release to officially support Angular 9.x?

**Comment by erwinwolff** [comment]
Yes, Angular 9 support would be great

**Comment by doublemcz** [comment]
Issue opened Feb 12, still no response?
`npm WARN @tinymce/tinymce-angular@3.5.0 requires a peer of @angular/core@>=5.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.`

**Comment by magnusbakken** [comment]
Angular 10 is out now, so might as well jump straight to that one.

In my opinion, authors of small libraries like this one could do themselves a big favor by optimistically setting their Angular peer dependencies to something like ">= 5.0.0", and just deal with the problems if there are actual issues when the next major version comes along.

**Comment by jscasca** [comment]
Hi,

We wanted to make to prepare a build supporting Angular 9 and were taking into account the impact it would have in our ability to keep supporting multiple versions. Initially we considered just updating the peer dependencies to avoid having warnings but were unsure what impact it would have with more recent versions of Angular. We have released version 4.0.0 of the wrapper to support Angular 10 which should be compatible with Angular 9.
