### ISSUE TITLE
Editor breaks when removed from template with animations

### ISSUE THREAD

**Issue by Ploppy3** [tinymce/tinymce-angular#137]
**What is the current behavior?**
Editor breaks when removed from template with animations.
It turns into a textarea during the animation.
I've tested several of my animations and all break the editor.

![gif](https://user-images.githubusercontent.com/7990765/74447137-2bbc6e00-4e79-11ea-8c14-75bd953e53db.gif)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6zlmmkkk1n?fontsize=14) or similar.**

https://codesandbox.io/s/tinymceangular-6kzby

```html
<div *ngIf="editorVisible" @fadeInOut>
  <editor required></editor>
</div>
```

```ts
export const fadeInOut = trigger('fadeInOut', [
  state('void', style({
    opacity: 0
  })),
  state('hidden', style({
    opacity: 0
  })),
  state('visible', style({
    opacity: 1
  })),
  transition(':enter, hidden => visible', [
    animate('.5s ease', style({
      opacity: 1,
    })),
  ]),
  transition(':leave, visible => hidden', [
    animate('.5s ease', style({
      opacity: 0,
    })),
  ]),
]);
```

**What is the expected behavior?**
Editor should not break when animated

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or TinyMCE-Angular?**
Angular 9 with Ivy
TinyMCE-Angular: 3.4.0

**Comment by Ploppy3** [comment]
Since it seems to be an angular limitation, one way to partially solve this would be to give an optional `@Input` parameter to delay the destruction of the TinyMce editor in the `ngOnDestroy` call.

**Comment by Ploppy3** [comment]
For reference, here is how a similar issue was fixed by another dev.
https://github.com/telerik/kendo-angular/issues/1018#issuecomment-589167663

**Comment by SimonFc** [comment]
Might be something that tinymce-angular can handle but I do wonder how. I think we want to avoid delaying the removal of TinyMCE through other means than life cycle hooks (and similar) as I imagine that it easily could lead to bugs. Perhaps this doesn't work for your use case but as a workaround you could take care of conditionally removing tinymce-angular via an animation callback. https://codesandbox.io/s/tinymceangular-lg26p?fontsize=14&hidenavigation=1&theme=dark

To be investigated

**Comment by Ploppy3** [comment]
@SimonFc even though what you propose works, I don't think it is applicable to router animations.

**Comment by Ploppy3** [comment]
I implemented your solution and it indeed does not work for router animations.
