### ISSUE TITLE
Useless Image reload triggered at keyup event

### ISSUE THREAD

**Issue by tim-boerner** [tinymce/tinymce-angular#138]
**What is the current behavior?**
If images were pasted or uploaded, so that you have `img` tags. Every single image is reloaded on every single keyup, which results in massive useless network traffic. 

**steps to reproduce**
set up everything as provided in docu
use any image as inital text, e.g.: `<img src=\"https://avatars2.githubusercontent.com/u/119815?s=280&v=4\"></img>` or just copy and paste something
focus editing area and start typing

 [example at codesandbox](https://codesandbox.io/s/goofy-varahamihira-03tfc)

**What is the expected behavior?**
Images should not be reloaded on every keyup or change

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue?**
Affected versions:
TinyMCE-Angular 3.4.0 / 3.3.0 / 3.2.0
Tested with Chrome Browser and TinyMCE 5.2.0

**Did this work in previous versions of TinyMCE or TinyMCE-Angular?**
Seams to work with TinyMCE-Angular 3.1.0

**Comment by tim-boerner** [comment]
![IssueTinyMCE-Angular](https://user-images.githubusercontent.com/28528071/74483953-e703f780-4eb7-11ea-925b-4e35a80069d1.png)

**Comment by SimonFc** [comment]
This only happens when you have the cache disabled, right? In any case I think this is something tinymce-angular might be able to fix

**Comment by tim-boerner** [comment]
Yes, only happens when cache is disabled

**Comment by tim-boerner** [comment]
When using the editor in inline mode and multiple editors at the same page, if also occurs when cache is enabled

**Comment by EduardHuck** [comment]
Any update on this issue? Currently breaks my application.

**Comment by tim-boerner** [comment]
@EduardHuck : thanks for the hint as well, i didn't check that. I was only testing normal keyup.
I am still on 3.1.0. All versions above are not useable for my application.

**Comment by tim-boerner** [comment]
With version 4.1.0 the issue is not anymore on keyup events, but input events. This has been introduced by commit https://github.com/tinymce/tinymce-angular/commit/fd56a51a61a16139ec8c28bf06038df50191ec7f

The excecution of the registered onChange callback somehow triggers the image reload.
https://github.com/tinymce/tinymce-angular/blob/6fd80c914b2593ec37e4f47504680246fca95a9e/tinymce-angular-component/src/main/ts/editor/editor.component.ts#L174

**Comment by tim-boerner** [comment]
i opened #207 which could help. It is not a complete fix, but reducing the image reload effect only to cases when a custom onChange callback is registered.

**Comment by etcamol** [comment]
I am also facing the same issue in my current application at many places.
Could you please share if you have any solution approach.

**Comment by jscasca** [comment]
Thanks for the PR and thank you for your patience. This should be merged and released shortly

**Comment by jscasca** [comment]
The current fix provided by @tim-boerner was released in v4.2.2.

**Comment by enoh-barbu** [comment]
This bug can be reproduced in react as well
