### ISSUE TITLE
Default color & font

### ISSUE THREAD

**Issue by BrutalCSkakan** [tinymce/tinymce-angular#146]
**Is your feature request related to a problem? Please describe.**
The default font color is black-ish, but my background is dark which leads to the text being "Invisible". Everytime when I open the editor I need to change the color to #fff.
It's the same thing with the font, the Default font is not my preferred font.

 **Describe the solution you'd like**
the [init] should be expanded to contain default_font, or a list of fonts where it automatically chooses the first font in the list to be the default one.
Exactly the same behaviour for color

 **Describe alternatives you've considered**
I dont have any other alternatives

**Comment by lnewson** [comment]
@BrutalCSkakan the default font family/color should be controlled by your [`content_css`](https://www.tiny.cloud/docs/configure/content-appearance/#content_css). Here's a blog post that goes into more detail: https://www.tiny.cloud/blog/how-to-change-the-default-font-family-size-and-color-in-tinymce/

**Comment by BrutalCSkakan** [comment]
But content_css wont add the color & font to the actual generated HTML code right? 
Which means that it's required to always provide a CSS when I distribute the HTML code? 

My system will in some cases return the whole HTML in an API endpoint to third-party vendors, I can't see how I should be able to make them implement an external CSS.. The styling should already be in the HTML?
