### ISSUE TITLE
Ugrading from 2.5.0 to 3.5.0 doesnt work

### ISSUE THREAD

**Issue by LokeshD01-dev** [tinymce/tinymce-angular#148]
In angular6 application , I have just updated the @tinymce-angular version from 2.5.0 to 3.5.0 and updated the tinymce from 5.0.0 to 5.2.0.

Below is the code from angular.json scripts
              "node_modules/tinymce/tinymce.min.js",
              "node_modules/tinymce/themes/silver/theme.min.js",
              "node_modules/tinymce/plugins/advlist/plugin.min.js",
              "node_modules/tinymce/plugins/autolink/plugin.min.js",
              "node_modules/tinymce/plugins/lists/plugin.min.js",
              "node_modules/tinymce/plugins/link/plugin.min.js",
              "node_modules/tinymce/plugins/image/plugin.min.js",
              "node_modules/tinymce/plugins/charmap/plugin.min.js",
              "node_modules/tinymce/plugins/print/plugin.min.js",
              "node_modules/tinymce/plugins/preview/plugin.min.js",
              "node_modules/tinymce/plugins/anchor/plugin.min.js",
              "node_modules/tinymce/plugins/textcolor/plugin.min.js",
              "node_modules/tinymce/plugins/searchreplace/plugin.min.js",
              "node_modules/tinymce/plugins/visualblocks/plugin.min.js",
              "node_modules/tinymce/plugins/code/plugin.min.js",
              "node_modules/tinymce/plugins/insertdatetime/plugin.min.js",
              "node_modules/tinymce/plugins/media/plugin.min.js",
              "node_modules/tinymce/plugins/table/plugin.min.js",
              "node_modules/tinymce/plugins/paste/plugin.min.js",
              "node_modules/tinymce/plugins/wordcount/plugin.min.js",
              "node_modules/tinymce/plugins/help/plugin.min.js",

After this update, am not getting the proper HTML editor. Please find the below screenshot

![image](https://user-images.githubusercontent.com/60741173/76516376-53efba80-6481-11ea-9380-6635f350b53b.png)

PS: self hosting the tinymce.

**Comment by jscasca** [comment]
Hi @LokeshD01-dev 

Does it work with the cloud version or is it just not working with your self hosted tinymce? Could you elaborate more on your setup?

**Comment by tinydylan** [comment]
Hi, 

As we haven't heard back from you, we don't have enough information to diagnose the issue. 

It would help us if you're able to provide a simple self-contained app demonstrating the issue using [codesandbox.io](https://codesandbox.io/s/6zlmmkkk1n?fontsize=14) or similar. If it's something specific to a self-hosted setup, then some instructions or an example project as a zip file would be useful.

For now, we'll close the issue. Feel free to reach out to us if you're still encountering problems and we'll be happy to help.

Many thanks
