### ISSUE TITLE
ngModel is not updated after using "Undo" and "Redo" features

### ISSUE THREAD

**Issue by lifemaster** [tinymce/tinymce-angular#15]
I use this editor with Angular 5. I make some changes in the editor and then tap button "Redo". My changes are returned and in preview I see actual result. But ngModel contains previous result. The same happens with "Redo" button. It seems "Undo" and "Redo" features don't update ngModel value. Is it a bug or maybe I did something wrong? Also "Undo" and "Redo" buttons don't invoke onChange event. The same happens with "Ctrl + Z" and "Ctrl + Y" hotkeys. Please check these cases.

**Comment by fyrkant** [comment]
Yes I think I need to add the undo and redo events to the change emitter for the ngModel thingie, I'll try and fix it and get it out today!

**Comment by fyrkant** [comment]
Released 1.0.9 with a fix for this!

**Comment by lifemaster** [comment]
It really works now! Thank you a lot!
