### ISSUE TITLE
how to change the language on fly, in tinymce-angular

### ISSUE THREAD

**Issue by chrispcb** [tinymce/tinymce-angular#150]
hi !

I initialize editor in fr_FR (from language and language_url options) for exemple. And I would like to change in ES language on fly from the external button on web page.

how to do ? (angular 8)

**Comment by jscasca** [comment]
hi @chrispcb 

Currently there is no way to change the language on the fly. You would have to re-load the editor so it initializes everything it needs in the new language.

**Comment by chrispcb** [comment]
@jscasca 

Ok thanks
