### ISSUE TITLE
TinyMCE editor won't load when project is compiled with --prod (ionic build --prod)

### ISSUE THREAD

**Issue by burggraf** [tinymce/tinymce-angular#160]
**What is the current behavior?**
If our Ionic 5.0.7 project is compiled with "ionic build --prod" then the editor won't completely load.  You can see the icons and menu, but no HTML is loaded into the editor, and the editor won't accept the focus.  You get a blank editor box with no way to edit anything.  You can View / Source Code from the Editor menu and see the html, and it looks fine, but nothing is ever rendered in the editor box.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6zlmmkkk1n?fontsize=14) or similar.**

**What is the expected behavior?**

The editor should function in exactly the same way it does when the application is complied without --prod (simply using ionic build).

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or TinyMCE-Angular?**

This is the first version of TinyMCE we've tried, and we are only using tinymce-angular 3.5.0:
"@tinymce/tinymce-angular": "^3.5.0"

**Comment by tinydylan** [comment]
We don't currently have support for Ionic, but it's something that we're considering for future development, as it's a very popular framework. Unfortunately, we don't have any definite plans or dates at this stage.
