### ISSUE TITLE
Issue with font family on mobile browser

### ISSUE THREAD

**Issue by sukhminderx** [tinymce/tinymce-angular#161]
Hi

I have an issue with font family used in the content. I used comics sans. It shows correctly in destip or laptop browsers but it is not shown jn mobile devices and is inherited from application as shown:

![Screenshot_20200503-043127_Chrome](https://user-images.githubusercontent.com/35064031/80909526-0fe99b00-8cf7-11ea-8df8-47586ce2ce00.jpg)

![Screenshot_20200503-043116_Chrome](https://user-images.githubusercontent.com/35064031/80909532-1710a900-8cf7-11ea-9bd2-8974832ca483.jpg)

Please let me know what can be the issue?
Do I need to add fonts somewhere?
How come right font is displayed in desktop browser??

**Comment by jscasca** [comment]
Hi @sukhminderx 

If a font is not installed in a particular device it will fallback to a different font. You can use the `custom_css` property of the TinyMCE editor to specify custom fonts. Look at this codepen for example: https://codepen.io/anon/pen/przvoq

Let me know if this helps

**Comment by sukhminderx** [comment]
Thanks for this
