### ISSUE TITLE
Angular 9: [(ngModel)] update on Siri Input

### ISSUE THREAD

**Issue by informatikTirol** [tinymce/tinymce-angular#163]
ngModel does not update after SIRI voice input on IOS 13.4. Also no (onChange) event is fired after SIRI input
Update does only take place after keyboard input

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or TinyMCE-Angular?**
    "tinymce": "^5.2.2",
    "@tinymce/tinymce-angular": "^3.5.2",
    "@angular-devkit/core": "^9.1.5",
  IOS 13.4

**Comment by jscasca** [comment]
hi @informatikTirol 

Thanks for bringing that up. NgModel is only being updated on `change keyup undo redo` events and SIRI input is not firing any of those thus not being updated. I'll have a PR to allow users to define their own events shortly

**Comment by informatikTirol** [comment]
Hi @jscasca 
cool, looking forward to test it, thank you..
