### ISSUE TITLE
Support angular 10

### ISSUE THREAD

**Issue by keatkeat87** [tinymce/tinymce-angular#170]
As title.
![image](https://user-images.githubusercontent.com/8691013/85711039-77313380-b719-11ea-8296-385ab9f66787.png)

I try --force update, Look like every just work fine.

**Comment by jscasca** [comment]
Hi @keatkeat87 

We have released a new version of the wrapper, version 4.0 to support Angular 10. Let me know if this helps

**Comment by mariojsnunes** [comment]
That's great, will try this!

Side question, are releases no longer updated here?
https://github.com/tinymce/tinymce-angular/releases

**Comment by jscasca** [comment]
Hi @mariojsnunes 

Thanks for bringing this up. I tagged the last couple of releases so they should be up there now!

Cheers,
