### ISSUE TITLE
After align by center or right checkbox in checklist does not change state

### ISSUE THREAD

**Issue by OSorokin** [tinymce/tinymce-angular#180]

**Comment by jscasca** [comment]
This doesn't seem to be related to the angular wrapper. I'll move this to the TinyMCE crowd.

**Comment by jscasca** [comment]
@OSorokin
This GitHub is for the angular-wrapper of TinyMCE only,  since the checklist plugin is a premium plugin you will need to contact the support team: https://support.tiny.cloud/hc/en-us/requests/new
