### ISSUE TITLE
ngFor directive filter not filtering the editor values

### ISSUE THREAD

**Issue by dssantana** [tinymce/tinymce-angular#183]
Editor values remain in the filtered records event though I'm filtering them.
Example below:

**Editor Config** 
`public defaultConfig: any = {
    height: 700,
    base_url: '/tinymce',
    suffix: '.min',
    plugins: [
      'noneditable emoticons advlist autolink lists link charmap anchor',
      'searchreplace visualblocks code',
      'insertdatetime table paste wordcount codesample'
    ],
    menubar: false,
    toolbar: false
    ]
  };`

**Editor tag**
` <mat-card-content>
        <div fxLayout="column" fxLayoutAlign="start stretch">
          <div style="max-height: 300px;" fusePerfectScrollbar>           
            <editor
              initialValue="{{ review.review || '' }}"
              [init]="defaultConfig"
              [inline]="true"
              [disabled]="true"
              (onInit)="handleEvent($event)"              
            >
            </editor>
          </div>
        </div>
      </mat-card-content>`

When using a filter directive in angular, my components are being filtered as per the filter criteria but when the last item remains (originally with no data in editor), it is showing data of filtered value in tinyMce editor. It's like the dom is being not refreshed.
Can you help me here please? Thanks

**Comment by jscasca** [comment]
Hi @dssantana 

I don't think I follow, what is the expected outcome here? What is being filtered filtered here? Can you provide a replication sandbox of the issue?

All I'm seeing is an `or` for the `review.review` value.

**Comment by dssantana** [comment]
Hi @jscasca 
Let's close the issue, I figured it. it is happening when using a trackId method. I took out the trackId of the ngFor and is filtering perfectly
<app-quote-item *ngFor="let row of filteredQuotes; index as i" [quote]="row" [index]="i"></app-quote-item>
