### ISSUE TITLE
Build error with Angular 6.0.2

### ISSUE THREAD

**Issue by zuologio** [tinymce/tinymce-angular#19]
I've integrated the package following the guide (https://www.tinymce.com/docs/integrations/angular2/)
The build now returns this error:

`ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/@tinymce/tinymce-angular/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

i ｢wdm｣: Failed to compile.`

It means that tinymce-angular is not supported on Angular 6?

**Comment by fyrkant** [comment]
No I think it should work fine with Angular 6, are you still having this problem?

**Comment by maximelafarie** [comment]
I also have this issue with Angular `5.2.11` with `@tinymce/tinymce-angular: '^1.0.9'`. 

The output is:
```
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/@tinymce/tinymce-angular/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

This issue is directly concerned by this issue: https://github.com/angular/angular/issues/21925

It's probably because `@tinymce/tinymce-angular`'s `package.json` looks like that:

```json
{
  "name": "@tinymce/tinymce-angular",
  "description": "Official TinyMCE Angular Component",
  "version": "1.0.9",
  "repository": "https://github.com/tinymce/tinymce-angular.git",
  "author": "Ephox Inc",
  "license": "Apache-2.0",
  "private": false,
  "dependencies": {
    "@angular/core": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "tslib": "^1.7.1"
  },
  "main": "bundles/tinymce-tinymce-angular.umd.js",
  "module": "esm5/tinymce-tinymce-angular.js",
  "es2015": "esm2015/tinymce-tinymce-angular.js",
  "typings": "tinymce-tinymce-angular.d.ts",
  "metadata": "tinymce-tinymce-angular.metadata.json"
}
```

⚠️ `dependencies` needs to be replaced by `peerDependencies` like that:
```json
  "peerDependencies": {
    "@angular/core": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "tslib": "^1.7.1"
  }
```

Because it actually imports `"@angular/core": "^5.2.0"` and so on, and on my project my Angular version is `5.2.11`.

**Comment by fyrkant** [comment]
This has been fixed in the latest few versions.
