### ISSUE TITLE
localization not working in tinymce-angular

### ISSUE THREAD

**Issue by snowchenlei** [tinymce/tinymce-angular#198]
``` typescript
<editor
            [init]="{
              height: 500,
              language_url: '/assets/tinymce/langs/zh_CN.js',
              language: 'zh-CN'
            }"
          ></editor>
```
But it's still in English. NetWork also Loaded this zh_CN.js.
![image](https://user-images.githubusercontent.com/26211283/96074518-75af9500-0edb-11eb-8fda-4fc421922858.png)
![image](https://user-images.githubusercontent.com/26211283/96074540-8829ce80-0edb-11eb-9bdb-bf3750440a87.png)

**Comment by jscasca** [comment]
Hi @snowchenlei 

You have a typo in your language selection, the correct value is `zh_CN`. You can find additional information in this page: https://www.tiny.cloud/docs/configure/localization/#exampleusinglanguage

Additionally, if you are not using a custom language pack you don't need to specify the `language_url` value. You can see an exmaple here: https://codesandbox.io/s/tinymceangular-forked-g1iel?file=/src/app/app.component.html
