### ISSUE TITLE
Image was broken in preview section but showing properly in Editor.

### ISSUE THREAD

**Issue by bobbytechie** [tinymce/tinymce-angular#199]
**What is the current behavior?**
Image(Accessing from service) was broken in preview modal window but showing properly in Editor.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6zlmmkkk1n?fontsize=14) or similar.**

![image](https://user-images.githubusercontent.com/45222207/96147072-96500d00-0f24-11eb-8f68-ebc1b01f4244.png)

**What is the expected behavior?**
Image should show properly in preview modal window same as like in Editor.

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or TinyMCE-Angular?**
Broken in Chrome and Edge due to recent security updates with same site cookie policy.

When keeping None in the cookie policy, image appearing fine but not when it is set to Lax or Strict.

**Comment by jscasca** [comment]
Unfortunately, there is nothing we can do from the Angular wrapper as this sounds like a Tinymce issue. This repository is only for issue regarding the angular wrapper and not the Tinymce editor.
