### ISSUE TITLE
How to pass a images_upload_handler into the editor?

### ISSUE THREAD

**Issue by JoelParke** [tinymce/tinymce-angular#20]
I have a project that is using the images_upload_handler in order to store images out on AWS.
Is there any way to pass the images_upload_handler function (blobInfo, success, failure) { ... }
to the editor?

**Comment by fyrkant** [comment]
You should be able to set it in the `[init]` settings object, just like you'd do with the vanilla TinyMCE.

**Comment by JoelParke** [comment]
You can't quite do that, if you want to place the called function in the component.  I ended up simply modifying the code and adding: 

```
     @Input() images_upload_handler: any;
     @Input() file_picker_callback: any;
```

within the EditorComponent and then had those inputs used in the initialize() function:
```
      images_upload_handler: this.images_upload_handler,
      file_picker_callback: this.file_picker_callback,
```

**Comment by fyrkant** [comment]
I'm not sure I understand what you mean with "You can't quite do that, if you want to place the called function in the component", can you show an example?

**Comment by ManyouRisms** [comment]
@JoelParke You can pass a image handler when you initialize your data, for example

`<editor [init]="getInitData()"></editor>`

..and then in your .ts: 

```private getInitData() {
  return {
    ...
    image_upload_handler: <the function>
  }
}

**Comment by fyrkant** [comment]
Closing this as I don't think this a bug.

**Comment by ItsRobbAllen** [comment]
I see this was just closed, but does anyone have a full code example of this working? I need to be able to handle uploads very specifically  and I've yet to get a single example working in Angular 6.

**Comment by kverchi** [comment]
> I see this was just closed, but does anyone have a full code example of this working? I need to be able to handle uploads very specifically and I've yet to get a single example working in Angular 6.

It works :) Just a small correction in getInitData() method, it should return  image**s**_upload_handler
So the result is somthing like this:
```
getInitData() {
    return {
      images_upload_handler: function (blobInfo, success, failure) {
        // Your implementation 
    }
  }
```
An example of image upload handler implementation is [here](https://www.tiny.cloud/docs/configure/file-image-upload/#images_upload_handler).
