### ISSUE TITLE
Editor not rendered on downgradeComponent from Angular 9 to AngularJS

### ISSUE THREAD

**Issue by mikykonst** [tinymce/tinymce-angular#201]
I try to insert Editor as Angular 9 component into AngularJS as directive.

`directive('emailForm', downgradeComponent({component: EmailComponent, downgradedModule: 'EditorModule'}))`

But its empty on the screen and there are no errors.

![image](https://user-images.githubusercontent.com/17960435/96901118-83e15080-149b-11eb-976a-1472114d4dc0.png)
![image](https://user-images.githubusercontent.com/17960435/96901148-8e034f00-149b-11eb-878f-e87ef012e382.png)

**Comment by arturovt** [comment]
Hey, I've just tried to downgrade the component that renders the `editor` and it works perfectly:

```ts
@Component({
  template: `
    <editor
      [init]="{
        height: 500,
        menubar: false,
        plugins: [
          'advlist autolink lists link image charmap print preview anchor',
          'searchreplace visualblocks code fullscreen',
          'insertdatetime media table paste code help wordcount'
        ],
        toolbar:
          'undo redo | formatselect | bold italic backcolor |       alignleft aligncenter alignright alignjustify |       bullist numlist outdent indent | removeformat | help'
      }"
    ></editor>
  `,
})
export class EditorWrapperComponent implements OnInit {
  @ViewChild(EditorComponent, { static: true }) editor!: EditorComponent;

  ngOnInit(): void {
    console.log('editor = ', this.editor);
  }
}

@NgModule({
  imports: [EditorModule],
  declarations: [EditorWrapperComponent],
})
export class EditorWrapperModule {}

declare const angular: typeof import('angular');

angular
  .module('tinymce-test', [])
  .directive(
    'editorWrapper',
    downgradeComponent({ component: EditorWrapperComponent }) as angular.IDirectiveFactory,
  );

@NgModule({
  imports: [BrowserModule, UpgradeModule],
})
export class AppModule implements DoBootstrap {
  constructor(private upgrade: UpgradeModule) {}

  ngDoBootstrap(): void {
    this.upgrade.bootstrap(document.body, ['tinymce-test'], { strictDi: true });
  }
}

platformBrowserDynamic().bootstrapModule(AppModule);
```

Result:

![image](https://user-images.githubusercontent.com/7337691/145925007-af52140a-134a-4ae6-ad06-de468dad8c73.png)

![image](https://user-images.githubusercontent.com/7337691/145925030-b331c2b1-8a49-49eb-a999-3335570f5470.png)

---

I'm not sure if anyone will be able to help you until a reproducible example is provided. At least I wasn't able to reproduce the described behavior, as you can see from my screens.

**Comment by jscasca** [comment]
I will be closing this but happy to open if anybody can provide a simple reproduction of the issue
