### ISSUE TITLE
Not Compatible with Ivy in Angular 9

### ISSUE THREAD

**Issue by bornagainraj7** [tinymce/tinymce-angular#203]
I am unable to use this in my Angular 9 project as I'm constantly receiving error regarding incompatible with Ivy
The Error is "This likely means that the library (@tinymce/tinymce-angular) which declares EditorModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy."

![Screenshot (168)](https://user-images.githubusercontent.com/43012371/99646247-42ca6500-2a76-11eb-85ec-1f13acee1b16.png)

@tinymce/tinymce-angular: 4.2.0
Angular version: 9.1.6
OS: Windows 10 x64

**Comment by mtpultz** [comment]
We're using it in Angular v9.x, and we just get warnings in the console:

![image](https://user-images.githubusercontent.com/599498/100162788-417bac80-2e69-11eb-91f8-d021025ec024.png)

**Comment by jscasca** [comment]
Hi @bornagainraj7 

The angular wrapper should work with Ivy. Have you tried restarting your angular server so that the module is loaded properly?

**Comment by jscasca** [comment]
@bornagainraj7 is this still an issue?
