### ISSUE TITLE
Upload image local

### ISSUE THREAD

**Issue by AlexisNarvaez97** [tinymce/tinymce-angular#212]
Hello, this is a query rather than an issue, do you have an example about adding an image from the local?

**Comment by jscasca** [comment]
Hey @AlexisNarvaez97 

Do you mean uploading local images? Here is a quick [code sandbox sample](https://codesandbox.io/s/tinymceangular-forked-5cvi6?file=/src/app/app.component.ts) of using the `images_upload_handler`, in case you have a server here is some documentation on how to implement the actual upload on the client side https://www.tiny.cloud/docs/general-configuration-guide/upload-images/#exampleusingimages_upload_handler and here is an example of the backend side https://www.tiny.cloud/docs/advanced/php-upload-handler/

Let me know if this helps

**Comment by AlexisNarvaez97** [comment]
Thanks @jscasca
