### ISSUE TITLE
toolbar_location seems not working

### ISSUE THREAD

**Issue by dskibin** [tinymce/tinymce-angular#213]
Hello 
I have following init object:
```
public tinyMceSettings = {
    toolbar_location: 'bottom',
    inline: true,
    statusbar: false,
    menubar: false,
    browser_spellcheck: true,
    skin_url: '/assets/tinymce/skins/ui/oxide-dark',
    plugins: 'wordcount advlist autolink lists link image searchreplace visualblocks fullscreen insertdatetime media table paste charmap print preview anchor',
    toolbar: 'undo redo | bold italic backcolor | formatselect | bullist numlist outdent indent | alignleft aligncenter alignright alignjustify | removeformat | link',
    contextmenu: false
};
```
And i see following picture:
<img width="1050" alt="изображение" src="https://user-images.githubusercontent.com/2069948/105491101-d6165580-5cc6-11eb-9876-975aa293815e.png">

Expected behavior is that toolbar appears at the bottom. 

We are using angular 9,  tinymce 5.6.2 and tinymce-angular 4.2.0

This feature worked well before i updated to latest versions.

Could any one point me to right direction? Thanks in advance!

**Comment by jscasca** [comment]
Hi @dskibin 

Just wanted to check if you could still replicate this issue with the latest Tinymce v5.7
