### ISSUE TITLE
Update Angular to version 11

### ISSUE THREAD

**Issue by vpetrusevici** [tinymce/tinymce-angular#214]
Hi. Can you update dependencies to Angular 11 please?
There is a problem now. Thanks.
![image](https://user-images.githubusercontent.com/40790510/105864155-b783c780-6002-11eb-874a-5510e4efe7c4.png)

**Comment by jscasca** [comment]
Hi @vpetrusevici 

Just released a new version that support Angular 11. We were updating our release process so thank you for your patience!

**Comment by vpetrusevici** [comment]
Thank you @jscasca
