### ISSUE TITLE
Does only display a textarea, no menu, no wysiwig

### ISSUE THREAD

**Issue by phil123456** [tinymce/tinymce-angular#22]
Hi,

just installed tinyMCE, following the doc, but not much to see just a resizable textarea

using angular 5.2.0

how do I fix this ?

regards

**Comment by fyrkant** [comment]
I need some more information about your implementation to be able to help you, do you have a repo I can look at or can you create a small reproduction somwehere?

**Comment by phil123456** [comment]
found out the issue, angular cli was not loading the css files

**Comment by fyrkant** [comment]
Ok, sounds good that you found the problem!
