### ISSUE TITLE
some other js events

### ISSUE THREAD

**Issue by kernyden** [tinymce/tinymce-angular#221]
Hey to everyone! Thx for the editor to work with tables.

<code>"@tinymce/tinymce-angular": "^3.6.1"</code>

It would be grateful to add events like <code>ResizeEditor </code> => <code>onResizeEditor</code>.

[source](https://www.tiny.cloud/docs/advanced/events/)

**Comment by jscasca** [comment]
PR #228 up for this feature request

**Comment by jscasca** [comment]
This was released in 4.2.2, sorry for the late notice
