### ISSUE TITLE
How to display dynamic value in dialog using angular

### ISSUE THREAD

**Issue by the-nine-tail** [tinymce/tinymce-angular#225]
I am trying to display dynamic value in dialog but getting value as _undefined_.

**Code:**
body: {
            type: 'panel',
            items: [{
              type: 'alertbanner', // component type
              level: 'info',
              text: \`${this.myname}\`,
              url: 'http://my.url',
              icon: 'question'
            }]
          },

**this.myname** should display my name but it shows _undefined_.
I am using tinymce version 5+ integrated with angular 11

**Comment by jscasca** [comment]
Hi @the-nine-tail that might be an issue with how you are declaring your variable. Here is a codesandbox of a dialog displaying a dynamic value: https://codesandbox.io/s/tinymceangular-forked-huqsz?file=/src/app/app.component.ts

Let me know if that helps
