### ISSUE TITLE
Unlocalized strings found

### ISSUE THREAD

**Issue by tmmiller6** [tinymce/tinymce-angular#233]
In our Angular application, in the localized strings we have noticed the following strings that are not localized.

For the table properties dialog, in the advanced tab and Border style dropdown, none of the options besides “None” are localized.

For the table menu’s Column menu item, the following are not localized:
Cut column
Copy column
Paste column before
Paste column after

For the image insert dialog, “Alternative description” is not localized.

In package.json, the dependencies section has the following:
    "tinymce": "^5.6.2",
    "tinymce-i18n": "^20.12.25",

Is there something that I’m missing?  I have looked in the strings files in tinymce-i18n/langs (like ja.js) and the strings mentioned above are not included.

<img width="483" alt="Screen Shot 2021-04-20 at 9 12 28 AM" src="https://user-images.githubusercontent.com/73195387/115420918-c5d42080-a1b8-11eb-8cc9-b5ed9cf4a798.png">
<img width="561" alt="Screen Shot 2021-04-20 at 9 12 51 AM" src="https://user-images.githubusercontent.com/73195387/115420931-c8cf1100-a1b8-11eb-806f-a35ea3fb8cf0.png">
<img width="479" alt="Screen Shot 2021-04-20 at 9 13 02 AM" src="https://user-images.githubusercontent.com/73195387/115420936-c967a780-a1b8-11eb-815b-c671473a3486.png">

**Comment by jscasca** [comment]
Hi @tmmiller6 ,

The Angular wrapper uses by default the cloud bundle from the CDN with their current language packs. If their language pack is incomplete, you can bring this to the [TinyMCE repository](https://github.com/tinymce/tinymce) or head over to https://www.tiny.cloud/get-tiny/language-packages/ and contribute with the current translations. As a workaround, you can always use a custom language file by specifying the file url as documented here: https://www.tiny.cloud/docs/configure/localization/#language_url

Hope this helps
