### ISSUE TITLE
Inline editor init fails when inside ngIf or ngFor.

### ISSUE THREAD

**Issue by liesahead** [tinymce/tinymce-angular#245]
**What is the current behavior?**
Currently getting such error when editor (editor is not in iframe but :warning: `inline` so it shouldn't happen) is initialized inside `ngFor` or `ngIf`. Due to this error toolbar for such editors is not displayed and content from `formControl` is not set on init.
![image](https://user-images.githubusercontent.com/32300784/118126383-ecc0f380-b400-11eb-9a2d-441ed8c36fdc.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6zlmmkkk1n?fontsize=14) or similar.**
Error is happening in `tinymce.js` (place marked in screenshot) because `documentOrShadowRoot` is for some reason not the document but some ancestor element for such editors.
![image](https://user-images.githubusercontent.com/32300784/118126546-28f45400-b401-11eb-9753-99f24457ae28.png)

**What is the expected behavior?**
No such errors. When editor is not in mat tabs or with `ngIf`/`ngFor` attribute it doesn't fail (screenshot of working editor attached below).

![image](https://user-images.githubusercontent.com/32300784/118126799-7d97cf00-b401-11eb-8763-e0864d8282ad.png)

We were able to fix it with some hack (not sure yet how stable it is). We have a wrapper component for angular-tinymce where we added a `viewInited` boolean variable. In `ngAfterViewInit` this variable is toggled to true. And it is used in template like so:

`<editor *ngIf="viewInited"></editor>`

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or TinyMCE-Angular?**

- "@angular/animations": "^11.2.13",
- "@angular/cdk": "^11.2.12",
- "@angular/common": "^11.2.13",
- "@angular/compiler": "^11.2.13",
- "@angular/core": "^11.2.13",
- "@angular/forms": "^11.2.13",
- "@tinymce/tinymce-angular": "^4.2.2",
- "tinymce": "5.8.0"

**Comment by jscasca** [comment]
It looks like it is referencing a removed element. It's a bit hard to tell without a replication case. Can you provide a simple replication?

**Comment by liesahead** [comment]
@jscasca , will create a repro this month (I hope even this week).

**Comment by danoaky-tiny** [comment]
As this issue has gone stale, I'm closing it for now. Feel free to open a new issue if this problem persists.
