### ISSUE TITLE
self hosted doesn't work with premium plugins

### ISSUE THREAD

**Issue by solomon23** [tinymce/tinymce-angular#247]
I have self hosted working but it tries to load the premium plugins from local instead of the cloud.  if in include the premium plugins .js and load it up first - that gives me a script error.  

The angular wrapper should take care of loading the cloud hosted premiums if the api key is present I imagine.  It doesn't seem like there is a way to use self hosted and premium at this time

**Comment by tiny-james** [comment]
When you are self hosting the editor you need to give the editor the location to load any plugins that you are not loading relative to `tinymce.min.js`. This is done by using the [`external_plugins` setting](https://www.tiny.cloud/docs/configure/integration-and-setup/#exampleusingexternal_plugins).

```html
<editor [init]="{external_plugins: { 'testing': 'http://www.testing.com/plugin.min.js',  'maths': 'http://www.maths.com/plugin.min.js' }}"></editor>
```
If you wish to get the plugins on cloud then they will be relative to the normal cloud URL that you can get from your [account page](https://www.tiny.cloud/auth/login/).

For example the link plugin is at:
```
https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins/link/plugin.min.js
```

**Comment by solomon23** [comment]
@tiny-james thanks for the support here.  I was able to use that method and it loaded the script successfully and I don't see it trying to load any bad scripts anymore.  But the mentions plugin isn't working

```
plugins: 'mentions autoresize',
external_plugins: {
          mentions: `https://cdn.tiny.cloud/1/${TINY_MCE_KEY}/tinymce/5/plugins.min.js`,
        },
```

Works fine if I don't self host but using this method nothing happens when i type `@`

**Comment by solomon23** [comment]
Thank you - that fixed me up
