### ISSUE TITLE
How do we add a custom button from our template?

### ISSUE THREAD

**Issue by ianhatton** [tinymce/tinymce-angular#25]
Hi there,

How do we add a custom button from our template? I have tried the following:

```
<editor
    [init]="{setup: function (editor) { editor.addButton('mybutton', { ... }); } }"
    toolbar="undo, redo, mybutton">
</editor>
```

But always receive "Missing expected }..." in the console.

I have also tried:

```
<editor
    (onInit)="initTinyMCE($event)"
    toolbar="undo, redo, mybutton"
</editor>
```

where the method called consists of the following:

```
initTinyMCE(event: any): void {
    event.editor.addButton('mybutton', { ... });
}
```

Using this second attempt, I can see 'mybutton' in the console when I log event.editor.buttons but it never appears in the toolbar alongside undo and redo. Am I missing something?

**Comment by fyrkant** [comment]
I can't seem to get it to work with having it inline in the template, but it seems to work if I reference a property on the class, so `<editor [init]="myConf"></editor>` where myConf is an object on the class.

**Comment by fyrkant** [comment]
So I just recommend doing that, don't think this is a problem with this component but a limitation in angular so I'm closing this.

**Comment by ianhatton** [comment]
Thank you! I was able to add my button using your approach.

**Comment by priyabhushansingh** [comment]
Hi @ianhatton can you please elaborate little bit how did you add customize button?
