### ISSUE TITLE
Update Angular to Version 12

### ISSUE THREAD

**Issue by hirokiterashima** [tinymce/tinymce-angular#252]
Hi. Can you update dependencies to Angular 12 please?

When trying to upgrade my project to Angular 12 with ```ng update @angular/core@12 @angular/cli@12```, the migration fails.

```
...
Package "@tinymce/tinymce-angular" has an incompatible peer dependency to "@angular/common" (requires ">=9.0.0 <11.0.0" (extended), would install "12.0.3").
...
Migration failed: Incompatible peer dependencies found.
```

**Comment by jscasca** [comment]
Hi @hirokiterashima What version of the tinymce-angular are you using? Currently, version ^4.2 peer dependencies requirements are `>=9.0.0` so that should work in theory

**Comment by hirokiterashima** [comment]
Hi @jscasca,

I had specified 4.2.0 in package.json, but it looks like my node_modules was messed up.
```
$ npm ls @tinymce/tinymce-angular
└── @tinymce/tinymce-angular@4.2.0  invalid
```

A clean install fixed it. Thanks for your help!
