### ISSUE TITLE
Cannot add formatting to wrap text in an <aside> tag

### ISSUE THREAD

**Issue by BenRacicot** [tinymce/tinymce-angular#255]
Trying to create two top-level buttons which wrap highlighted text in an `<aside>`.

Please see StackOverflow question: [stackoverflow.com/q/67953361/1440240](https://stackoverflow.com/q/67953361/1440240)

**What is the expected behavior?**

As shown in the StackOverflow question, after trying:

`block_formats: 'Paragraph=p;Heading 1=h1;Heading 2=h2;Heading 3=h3;Preformatted=pre;Aside=aside;'`
I have enabled the custom menu in a desperate attempt to add these buttons.

I've also read through all the documentation and cannot get anything to work as expected. 

Please help me get this working and perhaps create an Angular specific example for others.

**Comment by jscasca** [comment]
Hi @BenRacicot I believe you can achieve that by adding a custom format. For example:
```
block_formats: 'Paragraph=p;Aside=aside',
formats: {
  aside: {block: 'aside'}
},
```
I made an Angular example with a button to apply the aside format: https://codesandbox.io/s/tinymceangular-forked-5zv1p?file=/src/app/app.component.ts but not sure what exactly are you expecting. Maybe the guys in the [TinyMCE repo](https://github.com/tinymce/tinymce) can help you better understand formats?

**Comment by BenRacicot** [comment]
Wow @jscasca that was incredibly helpful! Thank you so much for your time and help on this. I was so very close but this clarified everything.

**Comment by jscasca** [comment]
Glad we could help!
