### ISSUE TITLE
How to show spinner until the tinymce editor is shown on the page

### ISSUE THREAD

**Issue by chelsumz007** [tinymce/tinymce-angular#257]
**Is your feature request related to a problem? Please describe.**
How to show spinner until the tinymce editor is shown on the page

 **Describe the solution you'd like**

 **Describe alternatives you've considered**

**Comment by jscasca** [comment]
That can be a bit tricky but if you have your own spinner implementation the callback needs to be placed in `init_instance_callback` to know the editor has finished loading
