### ISSUE TITLE
How can I let the form submit on Control + Enter instead of new line?

### ISSUE THREAD

**Issue by madhur** [tinymce/tinymce-angular#258]
**Is your feature request related to a problem? Please describe.**
I am currently using TinyMCE with angular application. Pressing Control + Enter adds a new line

 **Describe the solution you'd like**
Outside of TinyMCE, pressing control + enter submits the form. How can I have the same behavior from inside of TinyMCE

 **Describe alternatives you've considered**

**Comment by jscasca** [comment]
Hey @madhur 

You can probably add a [custom shortcut](https://www.tiny.cloud/docs/advanced/keyboard-shortcuts/#addcustomshortcutstotinymce) to handle your particular case. Here is a quick example: https://codesandbox.io/s/tinymceangular-forked-xljs4?file=/src/app/app.component.ts

Hope that helps
