### ISSUE TITLE
TinyMCE Angular doesn't show bullist or numlist - normal TinyMCE does.

### ISSUE THREAD

**Issue by plinkpaste** [tinymce/tinymce-angular#26]
Hi, We're having problems with TinyMCE Angular showing bullist and numlist options.

Our config is as follows - notice `lists` is present in `plugins`, and `bullist numlist` is present in `toolbar`.

```
this.tinyMceInit = {
	plugins: 'preview,searchreplace,paste,wordcount,lists,autoresize',
	branding: false,
	menubar: false,
	elementpath: false,
	gecko_spellcheck: true,
	toolbar: 'copy paste undo redo | bold italic underline bullist numlist',
	skin: 'customskin',
	valid_elements: 'strong/b,br,p,u,ul,ol,li,i/italic,em',
	invalid_elements: 'strike',
	extended_valid_elements: "span[style]",
	valid_styles: {'*': 'text-decoration'},
	autoresize_bottom_margin: 20,
	autoresize_max_height: 500,
	setup: function (editor) {
		editor.on('paste', function (e) {
			component.markFormAsDirty();
		});
	}
};
```

This results in the following editor:
![image](https://user-images.githubusercontent.com/7480500/43448324-923985e4-94a5-11e8-916d-3d6f4401e952.png)

**Notice that bullist and numlist are both missing.** 

Using the same config (minus the custom skin) on the same TinyMCE version without Angular **shows the options.** [See Fiddle here](http://fiddle.tinymce.com/Hxgaab).

![image](https://user-images.githubusercontent.com/7480500/43448507-0c6994b2-94a6-11e8-9fc1-f5bc2a77396b.png)

We're doing nothing with those options in the skin, so all the evidence points to an issue with TinyMCE Angular. Our `package.json` lists `@tinymce/tinymce-angular` as version `^2.0.0`.

**Comment by fyrkant** [comment]
How are you loading TinyMCE, are you using TinyMCE cloud or hosting by yourself?

**Comment by plinkpaste** [comment]
Self hosting.

**Comment by fyrkant** [comment]
Ok, are you loading the lists plugin in correctly? That's only reason I can think of that would keep it from being added to the toolbar.

**Comment by fyrkant** [comment]
Maybe check that the plugin is loaded by running `tinymce.activeEditor.plugins` and checking that it's included there.

**Comment by fyrkant** [comment]
It's not the same as the fiddle if you're hosting yourself, so the fiddle working doesn't show much I'm afraid. Can you share some more code on how your project is set up?

**Comment by plinkpaste** [comment]
I am confused as to how it's different? The underlying TinyMCE versions are the same (4.7.9).

However, here's all of the relevant TinyMCE code I've found in our project:

We import `tinymce-angular` into our module:
```typescript
import { EditorModule } from '@tinymce/tinymce-angular';
...
@NGModule({
...
imports: [..., EditorModule, ...]
...
}
```

In our parent component, we add the TinyMCE script:

```typescript
ngOnInit(): any {
	this.addScript('/scripts/tinymce4/tinymce.min.js', () => {
		this.addScript('/scripts/tinymce4/themes/modern/theme.js', null);
		}
	);
}
```

This is the TinyMCE code in our child component:

```html
<editor #tiny [formControl]="description" [init]="tinyMceInit"></editor>
```
```typescript
let component = this;
this.tinyMceInit = {
	plugins: 'preview,searchreplace,paste,wordcount,lists,autoresize',
	branding: false,
	menubar: false,
	elementpath: false,
	gecko_spellcheck: true,
	toolbar: 'copy paste undo redo | bold italic underline bullist numlist',
	skin: 'customskin',
	valid_elements: 'strong/b,br,p,u,ul,ol,li,i/italic,em',
	invalid_elements: 'strike',
	extended_valid_elements: "span[style]",
	valid_styles: {'*': 'text-decoration'},
	autoresize_bottom_margin: 20,
	autoresize_max_height: 500,
	setup: function (editor) {
		editor.on('paste', function (e) {
			component.markFormAsDirty();
		});
	}
};
```

That's all the code we have for TinyMCE in our Angular project.

**Comment by fyrkant** [comment]
The loading of tinymce is different, you are lazy loading it in your component, the fiddle is using a good ol' script tag. You have to make sure to load all the plugin js files correctly as well as tinymce and theme to make it work.

**Comment by plinkpaste** [comment]
Hi, thanks for your help. After more digging we found we were loading TinyMCE twice. After removing the second incorrect load, the icons now work.

I'll close this.
