### ISSUE TITLE
how to access TinyMCE in controller to dynamically change the height etc

### ISSUE THREAD

**Issue by aqkhana2002** [tinymce/tinymce-angular#263]
is there a way we can access TinyMCE in component ? like i want to change the height property or say i wanna change context menu item.

**Comment by jscasca** [comment]
@aqkhana2002  Sorry, I thought this had been answered. You can access the editor via the editor getter `editor`. For example:
```
@ViewChild(EditorComponent) editorView;
...
console.log(this.editorView.editor);
```

Or you can create a local reference via the editor setup function. For example:
```
editorRef;
  conf = {
    setup: (e) => {
      this.editorRef = e;
    }
  };
...
console.log(this.editorRef);
```

The previous answer should answer your other questions.
