### ISSUE TITLE
Have to refresh the page to get a second instance of TinyMCE to work

### ISSUE THREAD

**Issue by jimbeeer** [tinymce/tinymce-angular#264]
**What is the current behavior?**
I'm currently writing a CMS using TinyMCE, I go through the pages using routerLink. When I go to edit one page the editor works fine. When I go to edit a second page it hasn't destroyed the instance of the first one so it doesn't work. If I refresh the page then it works fine. If I use hrefs to navigate around, it works fine.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6zlmmkkk1n?fontsize=14) or similar.**

**What is the expected behavior?**
For the editor to work every time, or auto destroy itself on exit of the page. Is there a way to get it to destroy itself either within onInit or within onDestroy? I can't find any documentation anywhere supporting this.

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or TinyMCE-Angular?**
TinyMCE 5 for Angular. I don't know about previous versions.

**Comment by yangjunfocus** [comment]
I have same problem

**Comment by jscasca** [comment]
Please try to send replication cases when submitting bugs otherwise is really hard to look into them. I'm closing this until a replication is provided
