### ISSUE TITLE
Inline use causes Table to not resize inner cells

### ISSUE THREAD

**Issue by alextkd** [tinymce/tinymce-angular#267]
**What is the current behavior?**

When you use the inline mode table doesn't allow you to resize Rows and Columns 

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io]![image]

(https://user-images.githubusercontent.com/373321/134822142-4848295e-4366-45f1-af0c-a81ce083cfb6.png)
When I use the fixed toolbar it all works just fine and table resizes.

**What is the expected behavior?**
You should be able to do it in inline mode too. React library doesn't have this problem in inline mode.

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or TinyMCE-Angular?**

In the latest stable and the greatest 4.2.5-rc too.

**Comment by jscasca** [comment]
![angular_table](https://user-images.githubusercontent.com/6062777/134829601-75e0e07d-507a-481b-8ea0-ff9f1be0c34d.gif)

It seems to work on a normal sandbox. Can you send over a reproduction of the issue?
