### ISSUE TITLE
NPM warehouse does not exist 5.0 0 version

### ISSUE THREAD

**Issue by zjxcv7** [tinymce/tinymce-angular#275]
![image](https://user-images.githubusercontent.com/24834874/147719179-695c11cb-c99a-4a90-9e6e-2e7ea0975896.png)

**Comment by jscasca** [comment]
Thanks for bringing this up. I need to update a node in the CI to build and publish the latest. This might be out until the second week of Jan. Thanks for your patience!

**Comment by jscasca** [comment]
@zjxcv7 tinymce-angular v5.0.0 should be now available on npm
