### ISSUE TITLE
publish v5 on npm

### ISSUE THREAD

**Issue by de-dan** [tinymce/tinymce-angular#277]
**What is the current behavior?**

Version 5 is needed for Angular 13 support. Currently it is not possible to install Version 5 via npm (`npm install @tinymce/tinymce-angular`) as described in the projects README.md.

**What is the expected behavior?**

@tinymce/tinymce-angular@5 is listed on npm: https://www.npmjs.com/package/@tinymce/tinymce-angular

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or TinyMCE-Angular?**

5.x.x

**Comment by jnnwnk** [comment]
Experienced the same. Any news on this?

There is also no release tagged on github with version 5.x

What is the designed way to use it with angular 13 at the moment?

**Comment by jscasca** [comment]
Thanks for your patience. This was actually on me as I broke the CI system and need to update a couple of nodes before I can get the release build out. I hope to have this resolved as soon as possible.

**Comment by jnnwnk** [comment]
Thanks for feedback.
Do you have any idea about the schedule? We are currently evaluating different WYSIWYG editors for our project and need to decide if it's worth it to wait for the fix, to integrate TINY MCE on our own (currently experiencing some problems) or to go with a completly different solution.

**Comment by jscasca** [comment]
@de-dan @jnnwnk 

The package `@tinymce/tinymce-angular` v5.0.0 should be now available on npm
