### ISSUE TITLE
Metadata version mismatch

### ISSUE THREAD

**Issue by ashish-vijay** [tinymce/tinymce-angular#28]
Getting the below error while running ng serve with "@tinymce/tinymce-angular": "^2.0.0". 

ERROR in Metadata version mismatch for module /media/loop/New Volume1/next/adminpanel/node_modules/@tinymce/tinymce-angular/tinymce-tinymce-angular.d.ts, found version 4, expected 3

But if the project is reloaded this error will go and will compile successfully, but cant build the project using ng build.

**Comment by fyrkant** [comment]
What version of angular-cli are you using? Looking at the error message it makes me think that you are using a too old version.

**Comment by MarcoLeko** [comment]
Same problem here using: @angular/core: 4.3.6

**Comment by fyrkant** [comment]
Seems like the latest version of @angular/cli is 6.1.3 so I'd advise to update to a newer version or @angular/cli.

**Comment by ashish-vijay** [comment]
@fyrkant which version of tinymce should be used for an angular 4 project?

cc @MarcoLeko

**Comment by ashish-vijay** [comment]
Solved the issue by downgrading to tinymce-angular@1.0.0 for Angular 4 project.
