### ISSUE TITLE
Error - ^5.0.0 under Angular 13.1 - Cannot find module 'tinymce' or its corresponding type declarations

### ISSUE THREAD

**Issue by xprojects-de** [tinymce/tinymce-angular#280]
Error: node_modules/@tinymce/tinymce-angular/editor/Events.d.ts:2:41 - error TS2307: Cannot find module 'tinymce' or its corresponding type declarations.
Error: node_modules/@tinymce/tinymce-angular/editor/editor.component.d.ts:4:60 - error TS2307: Cannot find module 'tinymce' or its corresponding type declarations.

Angular 13.1.2 with common dependencies

Other packages:
- Angular Material 13.1.2
- ngrx 13
- @tinymce/tinymce-angular ^5.0.0

Version @tinymce/tinymce-angular ^4.0.0 still works under 13.1 but without Ivy...

Thanks

**Comment by jscasca** [comment]
@xprojects-de  I believe you just need to install `tinymce` to get the correct types

**Comment by xprojects-de** [comment]
Thanks. It´s woking...

**Comment by Trapulo** [comment]
I have same problem but I cannot fix it :(
imported:

    "tinymce": "5.10.3",
    "@tinymce/tinymce-angular": "^5.0.1",

**Comment by alastair-todd** [comment]
v5 of tinymce was the trick for me. Seems `RawEditorSettings` has been removed from v6

**Comment by jscasca** [comment]
@alastair-todd the latest version of the wrapper does not use `RawEditorSettings` as it needs to work with different versions of the Editor. Having any version installed should do the trick with `@tinymce/tinymce-angular` v^6.0.1

@Trapulo have you tried the latest version?

**Comment by alastair-todd** [comment]
@jscasca yes correct thanks. The readme probably needs an update.

Any reason for not bundling tinymce up with the angular package? I does seem an easy mistake to make....

**Comment by jscasca** [comment]
The latest version comes with the Tinymce v6 dependency so it bundles together but allows you to keep you Tinymce v5 dependency if you have that already installed.

**Comment by anasmak04** [comment]
Try with the latest version that works for me 
npm install @tinymce/tinymce-angular@7.0.0
