### ISSUE TITLE
Editor Component Memory leak

### ISSUE THREAD

**Issue by NicolasFernandez212** [tinymce/tinymce-angular#287]
**What is the current behavior?**
The Editor component is still kept in memory whereas i changed paged from my angular app.
I tried to use remove function tinymce and set global settings to null but nothing that i tried can remove editor component from the memory.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6zlmmkkk1n?fontsize=14) or similar.**
<img width="530" alt="Capture d’écran 2022-03-03 à 10 52 16" src="https://user-images.githubusercontent.com/85177894/156541043-a84bbd54-b50a-4d31-9fcf-92ec968432e4.png">
<img width="474" alt="Capture d’écran 2022-03-03 à 10 52 23" src="https://user-images.githubusercontent.com/85177894/156541056-db2d85ce-1f7e-47ed-8a54-236edeeffe19.png">

**What is the expected behavior?**
The memory should destroy the editor component

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or TinyMCE-Angular?**
tinymce-angular@4.2.0
<img width="467" alt="Capture d’écran 2022-03-03 à 10 57 03" src="https://user-images.githubusercontent.com/85177894/156541165-53d36990-75a8-4ee0-9c32-9d65baeac372.png">

In this closed issue it was said it was a resolved issue but why then i got memory leak from this component [https://github.com/tinymce/tinymce-angular/issues/90](url) ?

**Comment by marfyl** [comment]
I have the same problem [Issue90](https://github.com/tinymce/tinymce-angular/issues/90)
