### ISSUE TITLE
Plugins are not loading!

### ISSUE THREAD

**Issue by RRakib** [tinymce/tinymce-angular#292]
None of the plugins are loading after upgrading to ```@tinymce/tinymce-angular: 6.0.1```. It shows ```failed to load``` on api request. And it's trying to call for all the plugin in a single request. In older version they used to load one by one.

**Comment by jscasca** [comment]
What kind of setup do you have?

**Comment by xprojects-de** [comment]
Hello,
same here using Angular 14 (see errorImage).

package.json dependencies:
```json
{
    "@angular/animations": "^14.0.3",
    "@angular/cdk": "^14.0.3",
    "@angular/common": "^14.0.3",
    "@angular/compiler": "^14.0.3",
    "@angular/core": "^14.0.3",
    "@angular/elements": "^14.0.3",
    "@angular/forms": "^14.0.3",
    "@angular/material": "^14.0.3",
    "@angular/platform-browser": "^14.0.3",
    "@angular/platform-browser-dynamic": "^14.0.3",
    "@angular/router": "^14.0.3",
    "@ngrx/effects": "^14.0.0",
    "@ngrx/entity": "^14.0.0",
    "@ngrx/store": "^14.0.0",
    "@ngrx/store-devtools": "^14.0.0",
    "@tinymce/tinymce-angular": "^6.0.1",
    "chart.js": "^3.8.0",
    "ng-gallery": "^7.0.0",
    "ng2-charts": "^3.0.11",
    "ngx-mat-select-search": "^4.2.0",
    "rxjs": "~7.5.5",
    "tinymce": "^6.0.3",
    "tslib": "^2.4.0",
    "zone.js": "~0.11.6"
  }
```
Also uising tinyClous with API-Key and not selfHosted!

![Bildschirmfoto 2022-06-23 um 21 43 48](https://user-images.githubusercontent.com/55982921/175384463-10b20752-aa51-4ceb-a43a-258906885a33.png)

**Comment by xprojects-de** [comment]
ah sorry. i did a mistake. it´s working. Since 6.x the plugins are seperated by , not by whitespace!!
Thanks
