### ISSUE TITLE
NPM Package of @tinymce/tinymce-angular not updated properly

### ISSUE THREAD

**Issue by anupmca007** [tinymce/tinymce-angular#3]
Hi,
i am trying to take the tinymce-angular update using npm command like (npm i @tinymce/tinymce-angular or npm install @tinymce/tinymce-angular) but it is not comming properly, am try to integrate it throught angular project wrt url https://www.tinymce.com/docs/integrations/angular2/ .but it is not working .Because selector (editor) is not comming .Please check the  issue.

**Comment by fyrkant** [comment]
Can you share some more details about your project setup? Maybe share some code? Everything seems to work fine for me.

**Comment by anupmca007** [comment]
Project description:

Platform  windows10
a) Node version: v6.10.3
b) NPM version: 5.6.0
c) angular CLI: 1.6.3
d) angular : 5.1.3

The following steps what we followed are mentioned below:

Step 1. Install package using npm 
		npm install @tinymce/tinymce-angular
		
		
Step 2. Add required configuration according to your documention.

We have checked with latest version of angular 5.2.6, It is working fine. But we are using **angular version 5.1.3** then error is coming(**ERROR Error: StaticInjectorError[ElementRef]**)
in browser console and editor plugin is not working.

For more details, we are attaching the zip file.


[demo-tinymce-new.zip](https://github.com/tinymce/tinymce-angular/files/1747704/demo-tinymce-new.zip)

**Comment by fyrkant** [comment]
Thank you, I'll look into this.

**Comment by fyrkant** [comment]
Having a hard time understanding what's causing this. 🤔  

Are you able to update the angular version in you app to make it work?

**Comment by anupmca007** [comment]
Hi @fyrkant,
i am updating angular version , it is working fine. Thank you so much for provide the such imformation.

**Comment by Trapulo** [comment]
I've this error after I've upgraded to angular 5.2.10 and "@tinymce/tinymce-angular": "^1.0.7"

**Comment by fyrkant** [comment]
@Trapulo Can you share some more information about your project setup, maybe share some code?

**Comment by Trapulo** [comment]
sorry, a few days ago I've performed a big update to my project and now it is based on angular-cli, .net spaservices extensions, etc. and it's really different from the old one.
Now I've updated to 1.0.8 and seems ok, but, for example, webpack is now configured by angular-cli and not more with a custom config file.
