### ISSUE TITLE
tinymce-angular compatible with Angular 4.4.4?

### ISSUE THREAD

**Issue by john88benson** [tinymce/tinymce-angular#31]
Hi, 

I am looking to integrate the Rich Text Editing of TinyMCE in an Angular 4 project.  Are any of the older releases compatible?  If I try and npm install the latest it indicates it requires a peer of Angular 6 or greater.

Cheers,

-John

**Comment by john88benson** [comment]
I pulled down the 1.0.0 build and it looks like it needed 5.2.0.  I will leave this open for now in case there is an earlier build.

**Comment by fyrkant** [comment]
No unfortunately no older build available.
