### ISSUE TITLE
Form state doesn't update correctly when using ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by madmurl0c** [tinymce/tinymce-angular#311]
**What is the current behaviour**
When editing text in tinymce the form state doesn't update correctly.

**How to reproduce**
1. Open https://stackblitz.com/edit/angular-13-rmvnj2
2. Type in tinymce (state is not updated)
3. Type in regular input (state updates correctly)

**Expected behaviuor**
The form state should update automatically like it does with the regular input element.

**Comment by danobri** [comment]
Any updates on this?  I got tripped up by the same issue.  For anyone interested, to avoid removing ChangeDetectionStrategy.OnPush I am wired up the onSelectionChange event to a dummy function. 

**Template:**
```
<editor formControlName="comment" (onSelectionChange)="doNothing()"></editor>
```

**Class:**
```
// eslint-disable-next-line class-methods-use-this, @typescript-eslint/no-empty-function
doNothing() {}
```

**Comment by JustDoItSascha** [comment]
When will this be merged?

**Comment by danoaky-tiny** [comment]
Fixed in latest release (v8), closing.
