### ISSUE TITLE
RTC - Jwt provider error: expected it to return a promise

### ISSUE THREAD

**Issue by tmiljevic** [tinymce/tinymce-angular#312]
When trying to setup rtc plugin with the default init options from the [introduction](https://www.tiny.cloud/docs/tinymce/6/rtc-getting-started/#configure-the-required-tinymce-rtc-options),  `plugin.min.js:8 Jwt provider error: expected it to return a promise` error appears in the console and on the screen.

You can take a look at the demo here with the exact versions:

https://codesandbox.io/s/tinymce-angular-forked-vxyz7u

In my setup I'm using an api key from freshly created account.
I've also tried setting up an endpoint for rtc_token_provider, which indeed gets invoked but the same error persists.

Chrome Version 102.0.5005.61 (Official Build) (64-bit)
Mozilla Firefox 102.0.1 (64-bit)
OS Ubuntu 20.04.4 LTS

**Comment by jscasca** [comment]
@tmiljevic  For help with premium plugins you might need to head over to [TinyMCE support](https://www.tiny.cloud/docs/tinymce/6/support/)

With that said, the issue might be the plugin definition of "Promise" as everything inside Angular would use "ZoneAwarePromises" instead.

**Comment by tmiljevic** [comment]
@jscasca thank you! I will contact the support.

**Comment by jscasca** [comment]
Closing this ticket as it seems to be resolved :+1:
