### ISSUE TITLE
Initiating editor component take more then 6 seconds

### ISSUE THREAD

**Issue by chandiralekhasankar** [tinymce/tinymce-angular#317]
I have an Angular application and when I loading my component with editor component It will take more then 6 seconds to initiate the editor view

I am using angular version 14 and below
    "tinymce": "^6.0.3",
    "@tinymce/tinymce-angular": "^6.0.1",

Could any one support me to reduce the loading time.  (I already added the script and style in my project.json file)

**Comment by jscasca** [comment]
Is this being bundled together or are you using a CDN? Do you have a small replication we can look into or a benchmark in your environment?

**Comment by danoaky-tiny** [comment]
As this issue is quite stale, I'm closing it for now. Feel free to reply here or re-open a new issue if this problem persists.
