### ISSUE TITLE
Example app for tinymce-angular doesn't compile

### ISSUE THREAD

**Issue by rvwilliams88** [tinymce/tinymce-angular#320]
I'm just starting with tinymce-angular.  I have angular 14.2.6.  The full details are
Angular CLI: 14.2.6
Node: 16.14.2
Package Manager: npm 8.1.4
OS: win32 x64

Angular: 14.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.6
@angular-devkit/build-angular   14.2.6
@angular-devkit/core            14.2.6
@angular-devkit/schematics      14.2.6
@angular/cli                    14.2.6
@schematics/angular             14.2.6
rxjs                            6.6.7
typescript                      4.8.4
My package.json is 
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "cli": {
    "analytics": "a9276310-7ecc-47c9-9bf1-5de646d4a73b"
  },
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "tinymce-angular-demo": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:application": {
          "strict": true
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/tinymce-angular-demo",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kb",
                  "maximumError": "1mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "outputHashing": "all"
            },
            "development": {
              "buildOptimizer": false,
              "optimization": false,
              "vendorChunk": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true
            }
          },
          "defaultConfiguration": "production"
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "configurations": {
            "production": {
              "browserTarget": "tinymce-angular-demo:build:production"
            },
            "development": {
              "browserTarget": "tinymce-angular-demo:build:development"
            }
          },
          "defaultConfiguration": "development"
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "tinymce-angular-demo:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css"
            ],
            "scripts": []
          }
        }
      }
    }
  },
  "defaultProject": "tinymce-angular-demo"
}
I've tried the example given in the TinyMCE Docs as shown at https://www.tiny.cloud/docs/tinymce/6/angular-cloud/

When I try to compile the app using 'ng serve' I see the errors:
Error: node_modules/tinymce/tinymce.d.ts:702:63 - error TS2344: Type 'T' does not satisfy the constraint 'DialogData'.

702 declare type DialogActionHandler<T> = (api: DialogInstanceApi<T>, details: DialogActionDetails) => void;
                                                                  ~

  node_modules/tinymce/tinymce.d.ts:702:34
    702 declare type DialogActionHandler<T> = (api: DialogInstanceApi<T>, details: DialogActionDetails) => void;
                                         ~
    This type parameter might need an `extends DialogData` constraint.

Error: node_modules/tinymce/tinymce.d.ts:703:63 - error TS2344: Type 'T' does not satisfy the constraint 'DialogData'.

703 declare type DialogChangeHandler<T> = (api: DialogInstanceApi<T>, details: DialogChangeDetails<T>) => void;
                                                                  ~

  node_modules/tinymce/tinymce.d.ts:703:34
    703 declare type DialogChangeHandler<T> = (api: DialogInstanceApi<T>, details: DialogChangeDetails<T>) => void;
                                         ~
    This type parameter might need an `extends DialogData` constraint.

Error: node_modules/tinymce/tinymce.d.ts:704:63 - error TS2344: Type 'T' does not satisfy the constraint 'DialogData'.

704 declare type DialogSubmitHandler<T> = (api: DialogInstanceApi<T>) => void;
                                                                  ~

  node_modules/tinymce/tinymce.d.ts:704:34
    704 declare type DialogSubmitHandler<T> = (api: DialogInstanceApi<T>) => void;
                                         ~
    This type parameter might need an `extends DialogData` constraint.

Error: node_modules/tinymce/tinymce.d.ts:706:63 - error TS2344: Type 'T' does not satisfy the constraint 'DialogData'.

706 declare type DialogCancelHandler<T> = (api: DialogInstanceApi<T>) => void;
                                                                  ~

  node_modules/tinymce/tinymce.d.ts:706:34
    706 declare type DialogCancelHandler<T> = (api: DialogInstanceApi<T>) => void;
                                         ~
    This type parameter might need an `extends DialogData` constraint.

Error: node_modules/tinymce/tinymce.d.ts:707:66 - error TS2344: Type 'T' does not satisfy the constraint 'DialogData'.

707 declare type DialogTabChangeHandler<T> = (api: DialogInstanceApi<T>, details: DialogTabChangeDetails) => void;
                                                                     ~

  node_modules/tinymce/tinymce.d.ts:707:37
    707 declare type DialogTabChangeHandler<T> = (api: DialogInstanceApi<T>, details: DialogTabChangeDetails) => void;
                                            ~
    This type parameter might need an `extends DialogData` constraint.

Error: node_modules/tinymce/tinymce.d.ts:981:49 - error TS2344: Type '_0' does not satisfy the constraint 'DialogData'.

981 type PublicDialog_d_DialogSpec<_0> = DialogSpec<_0>;
                                                    ~~

  node_modules/tinymce/tinymce.d.ts:981:32
    981 type PublicDialog_d_DialogSpec<_0> = DialogSpec<_0>;
                                       ~~
    This type parameter might need an `extends DialogData` constraint.

Error: node_modules/tinymce/tinymce.d.ts:982:63 - error TS2344: Type '_0' does not satisfy the constraint 'DialogData'.

982 type PublicDialog_d_DialogInstanceApi<_0> = DialogInstanceApi<_0>;
                                                                  ~~

  node_modules/tinymce/tinymce.d.ts:982:39
    982 type PublicDialog_d_DialogInstanceApi<_0> = DialogInstanceApi<_0>;
                                              ~~
    This type parameter might need an `extends DialogData` constraint.

Error: node_modules/tinymce/tinymce.d.ts:1332:72 - error TS2344: Type 'T' does not satisfy the constraint 'DialogData'.

1332 declare type InstanceApi<T> = UrlDialogInstanceApi | DialogInstanceApi<T>;
                                                                            ~

  node_modules/tinymce/tinymce.d.ts:1332:26
    1332 declare type InstanceApi<T> = UrlDialogInstanceApi | DialogInstanceApi<T>;
                                  ~
    This type parameter might need an `extends DialogData` constraint.

Error: node_modules/tinymce/tinymce.d.ts:1334:34 - error TS2344: Type 'T' does not satisfy the constraint 'DialogData'.

1334     open: <T>(config: DialogSpec<T>, params: WindowParams | undefined, closeWindow: (dialog: DialogInstanceApi<T>) => void) => DialogInstanceApi<T>;
                                      ~

  node_modules/tinymce/tinymce.d.ts:1334:12
    1334     open: <T>(config: DialogSpec<T>, params: WindowParams | undefined, closeWindow: (dialog: DialogInstanceApi<T>) => void) => DialogInstanceApi<T>;
                    ~
    This type parameter might need an `extends DialogData` constraint.

Error: node_modules/tinymce/tinymce.d.ts:1334:112 - error TS2344: Type 'T' does not satisfy the constraint 'DialogData'.

1334     open: <T>(config: DialogSpec<T>, params: WindowParams | undefined, closeWindow: (dialog: DialogInstanceApi<T>) => void) => DialogInstanceApi<T>;
                                                                                                  
                  ~

  node_modules/tinymce/tinymce.d.ts:1334:12
    1334     open: <T>(config: DialogSpec<T>, params: WindowParams | undefined, closeWindow: (dialog: DialogInstanceApi<T>) => void) => DialogInstanceApi<T>;
                    ~
    This type parameter might need an `extends DialogData` constraint.

Error: node_modules/tinymce/tinymce.d.ts:1334:146 - error TS2344: Type 'T' does not satisfy the constraint 'DialogData'.

1334     open: <T>(config: DialogSpec<T>, params: WindowParams | undefined, closeWindow: (dialog: DialogInstanceApi<T>) => void) => DialogInstanceApi<T>;
                                                                                                  
                                                    ~

  node_modules/tinymce/tinymce.d.ts:1334:12
    1334     open: <T>(config: DialogSpec<T>, params: WindowParams | undefined, closeWindow: (dialog: DialogInstanceApi<T>) => void) => DialogInstanceApi<T>;
                    ~
    This type parameter might need an `extends DialogData` constraint.

Error: node_modules/tinymce/tinymce.d.ts:1341:34 - error TS2344: Type 'T' does not satisfy the constraint 'DialogData'.

1341     open: <T>(config: DialogSpec<T>, params?: WindowParams) => DialogInstanceApi<T>;
                                      ~

  node_modules/tinymce/tinymce.d.ts:1341:12
    1341     open: <T>(config: DialogSpec<T>, params?: WindowParams) => DialogInstanceApi<T>;     
                    ~
    This type parameter might need an `extends DialogData` constraint.

Error: node_modules/tinymce/tinymce.d.ts:1341:82 - error TS2344: Type 'T' does not satisfy the constraint 'DialogData'.

1341     open: <T>(config: DialogSpec<T>, params?: WindowParams) => DialogInstanceApi<T>;
                                                                                      ~

  node_modules/tinymce/tinymce.d.ts:1341:12
    1341     open: <T>(config: DialogSpec<T>, params?: WindowParams) => DialogInstanceApi<T>;     
                    ~
    This type parameter might need an `extends DialogData` constraint.

Error: node_modules/tinymce/tinymce.d.ts:1594:49 - error TS2344: Type '_0' does not satisfy the constraint 'DialogData'.

1594 type EventTypes_d_WindowEvent<_0> = WindowEvent<_0>;
                                                     ~~

  node_modules/tinymce/tinymce.d.ts:1594:31
    1594 type EventTypes_d_WindowEvent<_0> = WindowEvent<_0>;
                                       ~~
    This type parameter might need an `extends DialogData` constraint.

Is there a fix for this or a new version?

Richard Williams

**Comment by rvwilliams88** [comment]
I have fixed the problem for me by changing <T> to <T extends DialogData> whenever the error Type 'T' does not satisfy the constraint 'DialogData'. or similar occurs.  For example line 702 becomes
`declare type DialogActionHandler<T extends DialogData> = (api: DialogInstanceApi<T>, details: DialogActionDetails) => void;`

**Comment by jscasca** [comment]
That doesn't seem normal. What version of `tinymce` and `tinymce-angular` are you using? Also can you share a small replication of your case (a github repo should be fine) to help better understand the issue?

**Comment by rvwilliams88** [comment]
Hi

I've repeated the exercise again today, setting up the example from the documentation from scratch.  On further examination I found that there is a difference between the versions of typescript that were installed.  Yesterday, ***@***.*** had been installed but on repeating the exercise ***@***.*** has been installed.  I can confirm that the demo compiles correctly with ***@***.*** but fails with the errors I described with ***@***.***

I am at a loss to say why the installed versions of typescript were different on the two days as, as far as I know, the installations of Angular 14.2.7 and tinymce-angular were identical.
.

Regards



Richard Williams.



****************************************************

Richard Williams

email: ***@***.******@***.***>

mobile: 07981 734697

****************************************************



________________________________

**Comment by jscasca** [comment]
I think the email censored a lot of content. I guess they are npm packages but can't distinguish which one is which

**Comment by rvwilliams88** [comment]
Hi

I've created two repos for you to look at.  First is https://github.com/rvwilliams88/tinymce_1 which is the original example I tried and which does not compile.  The second is tinymce_2 which is the version created on my second attempt and which does compile.  The main difference as far as I can tell is the version of typescript.  As I said before I have no idea why the two examples ended up with this difference.

Regards

Richard Williams.

****************************************************
Richard Williams
email: ***@***.******@***.***>
mobile: 07981 734697
****************************************************

**Comment by lnewson** [comment]
Hi @rvwilliams88,

This is a known issue with the core TinyMCE types and TypeScript 4.8 or higher, see https://github.com/tinymce/tinymce/issues/8090. It has been fixed in TinyMCE 6.3.0 but has not been released yet, so for now the best option would be to stay on TypeScript 4.7 or lower as you've done in `tinymce_2`.
