### ISSUE TITLE
Problem with Angular 15

### ISSUE THREAD

**Issue by valeri879** [tinymce/tinymce-angular#327]
**What is the current behavior?**
after upgrading to angular 15, I also upgrade tinymc to 7.* version, but has an error 
" This type parameter might need an `extends DialogData` constraint. "

**What is the expected behavior?**

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or TinyMCE-Angular?**

> "dependencies": {
>     "@angular/animations": "^15.0.0",
>     "@angular/cdk": "^15.0.0",
>     "@angular/common": "^15.0.0",
>     "@angular/compiler": "^15.0.0",
>     "@angular/core": "^15.0.0",
>     "@angular/forms": "^15.0.0",
>     "@angular/material": "^15.0.0",
>     "@angular/platform-browser": "^15.0.0",
>     "@angular/platform-browser-dynamic": "^15.0.0",
>     "@angular/platform-server": "^15.0.0",
>     "@angular/router": "^15.0.0",
>     "@ng-select/ng-select": "9.0.2",
>     "@nguniversal/express-engine": "^15.0.0",
>     "@tinymce/tinymce-angular": "^7.0.0",
>     "express": "^4.15.2",
>     "firebase": "^9.4.0",
>     "localstorage-polyfill": "^1.0.1",
>     "material-design-icons": "^3.0.1",
>     "ng-recaptcha": "^10.0.0",
>     "prismjs": "^1.29.0",
>     "rxfire": "^6.0.0",
>     "rxjs": "~7.4.0",
>     "tslib": "^2.3.0",
>     "zone.js": "~0.11.4"
>   },
>   "devDependencies": {
>     "@angular-devkit/build-angular": "^15.0.0",
>     "@angular/cli": "^15.0.0",
>     "@angular/compiler-cli": "^15.0.0",
>     "@angular/localize": "^15.0.0",
>     "@nguniversal/builders": "^15.0.0",
>     "@types/express": "^4.17.0",
>     "@types/jasmine": "~3.10.0",
>     "@types/node": "^12.20.45",
>     "@types/prismjs": "^1.26.0",
>     "@types/tinymce": "^4.6.5",
>     "jasmine-core": "~3.10.0",
>     "karma": "~6.3.0",
>     "karma-chrome-launcher": "~3.1.0",
>     "karma-coverage": "~2.1.0",
>     "karma-jasmine": "~4.0.0",
>     "karma-jasmine-html-reporter": "~1.7.0",
>     "typescript": "^4.8.2"
>   }

**Comment by Abishek-Amstrong** [comment]
Facing the same issue after upgrading to angular 15 with Tinymce 7.0.0

**Comment by valeri879** [comment]
> Facing the same issue after upgrading to angular 15 with Tinymce 7.0.0

hope they will fix soon

**Comment by alexrutkov** [comment]
please, fix this compile errors

**Comment by valeri879** [comment]
guys I completly uninstall tinymce package and re-install new package called tinymce-angular
here is npm package https://www.npmjs.com/package/@tinymce/tinymce-angular
@alexrutkov @Abishek-Amstrong

**Comment by danoaky-tiny** [comment]
As this issue is quite stale, I'm going to close it for now. Feel free to open a new issue if any problems persist.
