### ISSUE TITLE
Error when editor tag is within an mat-tab from the 2nd tab and onward.    

### ISSUE THREAD

**Issue by EliJArmstrong** [tinymce/tinymce-angular#333]
### 1. What is the current behavior?

If the editor tag is placed in the 2nd tab of an angular materials tab group ([mat-tab](https://material.angular.io/components/tabs/overview)). I get an error in the console:

 `Cannot read properties of undefined (reading 'length')`.

 If the editor tag is placed within the first tab, then there is no problems.  

<pre>

</pre>

### 2. Please provide the steps to reproduce and if possible a minimal demo of the problem

Placing an editor in the 2nd mat-tab of a angular material [mat-tab-group](https://material.angular.io/components/tabs/overview)

Here is a stackblitz with the editor in the 2nd tab (error shows):
https://stackblitz.com/edit/angular-ivy-hbyt6o?file=src/app/app.component.html

Here is a stackblitz with the editor in the 1st tab (no error):
https://stackblitz.com/edit/angular-ivy-s9sqca?file=src/app/app.component.html

<pre>

</pre>

### 3. What is the expected behavior?

No errors when placing the <editor> in the 2nd tab ([mat-tab](https://material.angular.io/components/tabs/overview)).

<pre>

</pre>

### 4. Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue?

I'm using Chrome Version 108.0.5359.125 (Official Build) (64-bit)

I was able to reproduce this error in Angular Versions 14.2.2 and 15.0.4

I was using TinyMCE-Angular version 7.0.0 for both Angular versions above.

**Comment by danoaky-tiny** [comment]
See here for our storybook using Material tabs: https://tinymce.github.io/tinymce-angular/?path=/story/editor--material-tabs
Let us know if that helps.

Source:
https://github.com/tinymce/tinymce-angular/blob/20c1991d6d4f6326a13527b4c6076fca8362ec64/stories/materialtabs/MaterialTabs.component.html#L1-L9
https://github.com/tinymce/tinymce-angular/blob/20c1991d6d4f6326a13527b4c6076fca8362ec64/stories/materialtabs/MaterialTabs.component.ts#L1-L22

**Comment by danoaky-tiny** [comment]
I'm closing this for now as its become stale. Feel free to comment here or reopen a new issue if needed.
