### ISSUE TITLE
Issue in showing bullet and numeric list

### ISSUE THREAD

**Issue by uttam-panchal-nividous** [tinymce/tinymce-angular#334]
I am using Angular 15.

My editor code is like this:
`plugins: ['advlist autolink lists link image charmap print preview anchor',
              'searchreplace visualblocks code fullscreen',
              'insertdatetime media table contextmenu paste'
              ],
              toolbar:
                'undo redo | bold italic backcolor |
                bullist numlist outdent indent | removeformat'`

It is not showing bullet and numeric lists. Please see below.

![image](https://user-images.githubusercontent.com/98404124/209629484-4a528e50-daad-4b9c-a1ec-472a7d2794f0.png)

**Comment by EliJArmstrong** [comment]
Hello,

How I was able to get them to show was to set the plugins and toolbar in the HTML element.

```
<editor
     apiKey="" 
     plugins="preview  advlist lists wordcount help charmap quickbars emoticons"
     toolbar= 'undo redo | bold italic backcolor | bullist numlist outdent indent | removeformat'
></editor>
```

![image](https://user-images.githubusercontent.com/41320998/210011153-50a8c60a-b918-465e-b1af-34f5e3a1c65d.png)

**Comment by shanmen-tiny** [comment]
Hello @uttam-panchal-nividous,

Sorry for not getting back to this earlier. Yes, @EliJArmstrong's example is correct. It seems like you're using a TinyMCE 6 version but a TinyMCE 5 format to load the plugins. Arrays of space-separated strings are no longer supported in TinyMCE 6 and only these three plugin loading formats are supported: 
1. An array of strings
2. A space-separated string
3. A comma-separated string

Reference: https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/#plugin-loading-format-change

Feel free to reopen this issue if the issue persists. Thank you!
