### ISSUE TITLE
The editor's content is a blank text-area when setting the id

### ISSUE THREAD

**Issue by ktriek** [tinymce/tinymce-angular#34]
When giving the editor an id `<editor id="myid" ></editor>` it gives it an initial value of `<textarea id="myid"></textarea>`
![image](https://user-images.githubusercontent.com/4461059/45902428-68835300-bdb4-11e8-9f53-d00c3e924ffa.png)

[demo](https://stackblitz.com/edit/angular-kavpv2?file=src/app/app.component.html)

**Comment by fyrkant** [comment]
Whoah, that's weird! I'll have a fix out later today.

**Comment by fyrkant** [comment]
This should now be fixed in `v2.1.0`.
