### ISSUE TITLE
Issue when integrating TinyMCE  Angular v7 with Angular v15 and ABP v7

### ISSUE THREAD

**Issue by phuclong6384** [tinymce/tinymce-angular#341]
I would like to integrate TinyMCE Angular with ABP and follow every step in the official document: https://www.tiny.cloud/docs/tinymce/6/angular-cloud/
but the strange error happen.

Is there anyone meet the same issue and knows how to fix ? 

Error:
![image](https://user-images.githubusercontent.com/16498870/216734607-2c612677-b770-4d94-b9bc-43547fecd4b2.png)

Html:
![image](https://user-images.githubusercontent.com/16498870/216734897-3b0f541e-d7db-437b-af2a-5f72cfb1a129.png)

packages:
![image](https://user-images.githubusercontent.com/16498870/216734725-ec948489-2c97-4785-ad90-3a496105572f.png)

import module:
![image](https://user-images.githubusercontent.com/16498870/216735203-b2b9ed0a-3c78-475e-aa16-668811d65b03.png)

**Comment by danoaky-tiny** [comment]
It's hard to know for sure whether this is an issue with TinyMCE or ABP. Could you please provide a code sandbox (or similar) that replicates your issue.
You can fork this [code sandbox](https://codesandbox.io/p/devbox/tinymce-angular-v17-mppwf9) if you'd like.

**Comment by danoaky-tiny** [comment]
I'm closing this for now as its become stale. Feel free to comment here or reopen a new issue if needed.
