### ISSUE TITLE
Form control not updated with changes in the "code" plugin

### ISSUE THREAD

**Issue by bfredo123** [tinymce/tinymce-angular#343]
I am using TinyMCE 5.8.2 and Tinymce-angular 4.0.0 (Angular 12 app).
In a reactive form, I have:
```
          <editor formControlName="body" [init]="tinyInit"></editor>
```
Everything works fine except when the user modifies the html code via the "<>" code plugin button: the changes appear in the TineMCE box, but the value is not updated in the Angular form (I could also observe via `form.valueChanges.subscribe` that the change is not seen by Angular).

However, the SetContent event is properly fired.

This seems to be a random behavious unfortunately. And more likely to happen when changing the <head> section of the code (I have added the "fullpage" plugin, btw).

Any suggestion please to make this work?

Many thanks!

**Comment by jscasca** [comment]
You might have to change the model events used and add either `setcontent` or `closewindow` as `<editor modelEvents="change input undo redo setcontent closewindow">`.

Model events determine what triggers the editor value to propagate up the Angular chain so by default it only happens on `change input undo redo`. If you want a custom behaviour you can change this value.

**Comment by bfredo123** [comment]
Thank you so much jscasa! It works! Actually I removed setcontent because it triggers some extra things in my case, closewindow is just fine.
