### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by RanjithS99** [tinymce/tinymce-angular#344]
Which versions of TinyMCE/TinyMCE-Angular version supports angular 12.2.18?

**Comment by lorenzo-pomili** [comment]
you can check it here: https://www.tiny.cloud/docs/tinymce/6/angular-ref/#supported-angular-versions

**Comment by danoaky-tiny** [comment]
Slightly updated list: https://github.com/tinymce/tinymce-angular#support

**Comment by mmccaugh-polaris** [comment]
The "Slightly updated list" says to use version 8 for Angular 16+, but this version does not exist:

For Angular 16+, use integration version 8.x:

`npm install @tinymce/tinymce-angular@^8`

Running that command yields:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @tinymce/tinymce-angular@^8.

```

**Comment by danieloakman** [comment]
@mmccaugh-polaris Yes, the latest release failed in CI, apologies. We're on it
