### ISSUE TITLE
[disabled]="true" not working with angular v15.

### ISSUE THREAD

**Issue by ProfessionProgrammer** [tinymce/tinymce-angular#348]
**What is the current behavior?**
[disabled]="true" not working with angular v15. Before upgrading to 15, I was using angular 14, where it was working as excpected. only changes i have done is upgrade angular to v15.

![228778871-41d42e77-1ff8-47ba-bfbe-25bc61b834a1](https://user-images.githubusercontent.com/19427487/228828252-1bb6face-904e-4989-a8f0-8330120b1b0a.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6zlmmkkk1n?fontsize=14) or similar.**
![228779182-d7054bff-76f9-4df7-8a9e-a6ebb58e0cc2](https://user-images.githubusercontent.com/19427487/228828320-2440bb67-1721-4f65-8915-38f361a9c97d.png)
<br/><br/>
![228779940-1b0ec41c-2035-42d4-8335-3185b0d549c7](https://user-images.githubusercontent.com/19427487/228828427-473bc5e4-5d3b-43bc-85c3-905e29f8ce65.png)
<br/>

**What is the expected behavior?**

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or TinyMCE-Angular?**

![228755251-019f61c3-b37d-42ad-b0e2-6b17594a0cb9](https://user-images.githubusercontent.com/19427487/228828803-5be264e7-87e3-46d8-bdde-f9b18fceed3d.png)
<br/><br/>
![image](https://user-images.githubusercontent.com/19427487/228829052-ef918da5-31ba-4939-8651-239c89605fef.png)

**Comment by SherifMoShalaby** [comment]
+1
Am having the same issue

**Comment by BrunoElo** [comment]
There was an issue in angular v15 regarding disable not working in template. This link may help https://github.com/angular/angular/issues/48350#issuecomment-1400971435

**Comment by timrasche** [comment]
This doesnt work in angular 16 also...

**Comment by dezsiszabi** [comment]
I was able to fix this by adding a `<form>` tag around the `<editor></editor>` and setting the `name` attribute on the editor. For example:

```
<form>
  <editor name="editor"
          [(ngModel)]="model.value"
          [init]="editorOptions"
          [disabled]="true">
  </editor>
</form>
```

This works for me.

**Comment by MircoEnnova** [comment]
For me it was not possible to add a `<form>` tag. A temporary solution is using `editable_root` property.
```
<editor [init] = "{
    ...
    editable_root: false,
    ...
}"
</editor>
```
This works only on init though. But for my needs is good enough..
