### ISSUE TITLE
Getting ESMA Script issue in angular

### ISSUE THREAD

**Issue by abhinavek** [tinymce/tinymce-angular#356]
```
./node_modules/@tinymce/tinymce-angular/fesm2015/tinymce-tinymce-angular.mjs 581:163-175
Can't import the named export 'CommonModule' from non EcmaScript module (only default export is available)
```
Getting above error while calling <editor> in angular component
tried with  TinyMCE-Angular@7 and TinyMCE-Angular@6

Angular version using

Angular CLI: 8.3.26
Node: 16.15.1
OS: win32 x64
@angular/cdk                      8.2.3
@angular/cli                      8.3.26
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.3
@ngtools/webpack                  8.3.29
@schematics/angular               8.3.26
@schematics/update                0.803.26
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

**Comment by danoaky-tiny** [comment]
For Angular 8 and below try using `"@tinymce/tinymce-angular": "^3.0.0"`.
See https://github.com/tinymce/tinymce-angular#support
Let us know how that goes.
