### ISSUE TITLE
Update TinyMce

### ISSUE THREAD

**Issue by markusfalk** [tinymce/tinymce-angular#357]
**Is your feature request related to a problem? Please describe.**
I have problems with the outputted html from text that I paste into the editor.

 **Describe the solution you'd like**
From testing around on the tiny mce website I believe this problem is solved with the latest version of tiny mce. 
Are you planning to update tiny mce to version 6.x? It seems this angular wrapper is still using 5.x. 

 **Describe alternatives you've considered**
- Use tiny without the angular wrapper. 
- Use an update custom fork
- Create merge request with update?

Thank you :)

**Comment by TinyITAdmin** [comment]
Ref: INT-3204

**Comment by danoaky-tiny** [comment]
You can specify which version of TinyMCE is used with the [cloudChannel](https://www.tiny.cloud/docs/tinymce/6/angular-ref/#cloudchannel) input prop. By default this is the latest enterprise release.
