### ISSUE TITLE
How do I add a custom button to the toolbar?

### ISSUE THREAD

**Issue by eduardkennethlu** [tinymce/tinymce-angular#358]
Hi,

I would like to add a custom button that will apply a CSS letter spacing styling. I have seen the TinyMCE documentation and some examples over the net, but it is always written in jQuery.

Please help..

**Comment by TinyITAdmin** [comment]
Ref: INT-3205

**Comment by danoaky-tiny** [comment]
There's a number of different ways to create custom buttons in TinyMCE. Here is one example of a custom toggle button in the toolbar: https://www.tiny.cloud/docs/tinymce/latest/custom-toggle-toolbar-button/
If you have a look on the left side bar you'll find a number of different examples for creating custom buttons, menu items, etc.
