### ISSUE TITLE
Angular 6 + Reactive forms: How to clear editor content?

### ISSUE THREAD

**Issue by MaksimTikhon** [tinymce/tinymce-angular#36]
Why the code below does not clear editor content?
`this.form.controls.editor.setValue(null);`

I can clear the content using the next code: 
`this.form.controls.editor.setValue('<p></p>')`

It would be great to have an opportunity to set null/undefined to the control and expect that editor content will be empty after that and control value will not contain some html code.

**Comment by kqadem** [comment]
Have a look at [this line](https://github.com/tinymce/tinymce-angular/blob/master/tinymce-angular-component/src/editor/editor.component.ts#L63). 

Passing `null` will default tol the  initial  value.

**Comment by MaksimTikhon** [comment]
@kqadem thank you!
