### ISSUE TITLE
OnChange and onFocusOut event

### ISSUE THREAD

**Issue by kylianleem** [tinymce/tinymce-angular#361]
**What is the current behavior?**
When I have `[inline]="true"` and use the `onChange()` function or `onFocusOut(`)  function I expect them to be fired totally at the end of editting text. 

But when I change the "font family" or "font size" or changing "heading", actually all events with a dropdown are fired already before really finishing editing. Because of two way binding which is emited back to my component it closes the inline edit toolbar automatically for me so I need a function totally at the end of editting. 

Am I using the wrong functions, that there is another function that is called totally at the end of editting, or is this a bug?

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6zlmmkkk1n?fontsize=14) or similar.**
https://codesandbox.io/s/tinymce-angular-forked-7nv6zm

**What is the expected behavior?**
A function that is called at the end when the toolbar is closed and not when in editting mode still.

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or TinyMCE-Angular?**
Using chrome and TinyMCE-Angular ^7.0.0

**Comment by danoaky-tiny** [comment]
The blur event I think is what you're looking for, see: https://codesandbox.io/p/sandbox/new-tree-p8jm6d

Let us know if you need any further help.
