### ISSUE TITLE
Angular does not detect changes with events from the `<editor>` component 

### ISSUE THREAD

**Issue by franklbt** [tinymce/tinymce-angular#363]
**What is the current behavior?**

- Add the `<editor>` component to a parent component that should also display a template based on a state
- Use one of the provided component event (for example `(onBlur)`)
-update the state of the parent compoent (in the onBlur callback in this case)
- The updated state is not reflected on the view (since the callback is not executed in the angular zone)

**What is the expected behavior?**

The state is executed in angular zone

- TinyMCE: 6.6.2
- TinyMCE-Angular 7.0.0
- Browser / OS : all
- Did this work in previous versions of TinyMCE or TinyMCE-Angular? I don't know

Note: I managed to use the onBlur event by wrapping the callback inside a NgZone.run call, but this behaviour doesn't seems normal and is apparently not documented anywhere.

**Comment by TinyITAdmin** [comment]
Ref: INT-3225

**Comment by danoaky-tiny** [comment]
Could you please create a code sandbox or similar that replicates this issue and then share that with us?
You can fork [our code sandbox](https://codesandbox.io/p/devbox/tinymce-angular-v17-mppwf9) if you'd like.

**Comment by danoaky-tiny** [comment]
@franklbt I've made a code sandbox from the description of your issue https://codesandbox.io/p/devbox/int-3225-g4kkgf.
Although, I can't seem to replicate. Please feel free to fork that code sandbox to give us a better idea of what the problem is.

**Comment by danoaky-tiny** [comment]
I'm closing this issue as it has become stale. Feel free to comment here or create a new issue if the problem persists, but please first try replicating with the newest release (v8).
