### ISSUE TITLE
“Format” menu not working in Safari

### ISSUE THREAD

**Issue by adventmedia** [tinymce/tinymce-angular#369]
## 📝 To reproduce
Using Angular and Safari versions noted below:
1. Click on the “Format” menu item

### ✔️ Expected result
Format menu appears

### ❌ Actual result
Although menu item highlights, menu does not appear.
Observed in console: `TypeError: undefined is not an object (evaluating 'Ca(t).toLowerCase’)`

## 📃 Other details
- Browser: Safari 17.2
- OS: MacOS 14.2 (Sonoma)
- Angular: 17.0.2
- npm package: @tinymce/tinymce-angular:^7.0.0
not observed in previous versions of Safari.
does not occur in current version of Chrome

**Comment by danoaky-tiny** [comment]
As @TheSpyder mentioned, here is our our [code sandbox](https://codesandbox.io/p/devbox/tinymce-angular-v17-mppwf9), feel free to fork that and we can help further.

**Comment by danoaky-tiny** [comment]
I'm closing this for now as it's become stale, feel free to re-open a new issue if needed.

**Comment by adventmedia** [comment]
finally got around to killing this bug - took the better part of a day. Solution: uninstall `@ungap/custom-elements` — not even sure why it’s there but it appears to be a polyfill that is not only no longer necessary but causing the Format menu to fail.
