### ISSUE TITLE
Angular - declare tinymce init error

### ISSUE THREAD

**Issue by ChoYeongHoon** [tinymce/tinymce-angular#370]
version: 4.9.11

declare let tinymce: any;

ngOInit() void {
...
tinymce.init({
  selector: "#tinymce",
  menubar: true,
  toolbar: true
});
...
}

I am using a Javascript library in the Angular environment.
There is a problem creating an Editor through declare on the screen you want to use.
If you go to route and go to another screen, the editor stops.
The information you entered will disappear and you will not be able to enter new information.

Can you tell me what the phenomenon is?
(I tried to apply it with npm install, but it did not install in the project I am working on, so I used declare)

**Comment by danoaky-tiny** [comment]
It seems like you might not be using the `@tinymce/tinymce-angular` package? If that's the case, you'd be best off trying to use that instead as it will handle TinyMCE initialisation for you. It's an Angular specific wrapper for TinyMCE.

You can find a quick start guide here: https://www.tiny.cloud/docs/tinymce/6/angular-cloud/
You can also find the docs for the `<editor>` component here: https://www.tiny.cloud/docs/tinymce/6/angular-ref/

Let us know if that helps or if you have any other questions.
