### ISSUE TITLE
UI issue when insert new link

### ISSUE THREAD

**Issue by RahmanGhaffar** [tinymce/tinymce-angular#372]
![image](https://github.com/tinymce/tinymce-angular/assets/64298786/43e304d4-60e7-4f3c-87b3-e08d747818fc)
i try to insert new link when edit my content. then, this happen. can you guys help me fix this?

**Comment by danoaky-tiny** [comment]
Could you please provide a code snippet, a [code sandbox](https://codesandbox.io/p/devbox/tinymce-angular-v17-mppwf9) or something similar? Then we can investigate further

**Comment by danoaky-tiny** [comment]
I'm closing this as it's become stale. Feel free to reply here or re-open a new issue if this problem persists.
