### ISSUE TITLE
Need Support for Angular v15 / v16 / v17

### ISSUE THREAD

**Issue by mgardi85** [tinymce/tinymce-angular#373]
Currently the package does not articulate the support/ compatibility for Angular 14+. Since Angular v15 is nearing end of support a proper roadmap & support path will be helpful
We are planning to upgrade our application to Angular 16 but without a confirmation on support we cannot move

Additionally the package tinymce-angular@^7.0.0 was published more than a year back . so do we expect another release in line with core release of Tinymce Editor on 20th Mar

**Comment by danoaky-tiny** [comment]
I can confirm there is a planned update to support TinyMCE version 7. Additionally, support for Angular 15-17 is already in #367. So it's likely we'll have both in the same next release

**Comment by AlexWayOfElendil** [comment]
Hope we will get next release soon. Thanks for your work :)

**Comment by dharitdesai** [comment]
when are we planning to release the next version ? thanks!

**Comment by danoaky-tiny** [comment]
tinymce-angular v8 was just released now. See the [updated readme](https://github.com/tinymce/tinymce-angular?tab=readme-ov-file#support).
