### ISSUE TITLE
Window not defined when use angular-tinymce with angular ssr

### ISSUE THREAD

**Issue by Twois** [tinymce/tinymce-angular#38]
[angular ssr tinymce window / document is not defined]

Angular ssr crash if <editor formControlName="something" [init]="tinymceInit"></editor> is in the html, because tinymce use dom specific object that are not exists on server side.

After a while I was able to find a simple workaround. I just hide the tinymce if the page on sever side as follow: 
```
<editor *ngIf="isPlatformBrowser" formControlName="something" [init]="tinymceInit"></editor>
```

You can get the is isPlatformBrowser variable, just you have to inject it into the constructor:
```
export class AppModule {
    constructor(
        @Inject(PLATFORM_ID) private platformId: Object,
        @Inject(APP_ID) private appId: string,
    ) {
        const self = this;

        self.isPlatformBrowser = isPlatformBrowser(platformId);
    }
}
```

This is working for me, but I think it should be handled by tinymce-angular itself.

**Comment by fyrkant** [comment]
I've added this to the component now, can you try if it works for you?

**Comment by Twois** [comment]
@fyrkant Thank you! I was able to build the project correctly :)
