### ISSUE TITLE
Event dont pass the $eventObj

### ISSUE THREAD

**Issue by Twois** [tinymce/tinymce-angular#40]
1. When binding events to an editor, when the event handler gets called, it does not contain the event or the editor properties.

2. when adding the auto_focus field to the tiny init data, it wont now focus the editor.

```
<editor (onSetContent)="handleEvent($eventObj)" *ngIf="isPlatformBrowser" formControlName="text" [init]="tinymceInit"></editor>
```

```
self.tinymceInit = {
           "plugins": 'image link lists textcolor',
           "toolbar": 'bold italic strikethrough forecolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat',
           "menubar": '',
           "resize": false,
           "height": "100%",
           "auto_focus": true,
           "skin_url": '/assets/skins/lightgray',
           "forced_root_block" : 'div'
       };
```

```
public handleEvent(event){
       console.log(event); // undefined
}
```

We got this error when we tried to solve to focus the editor after its content set.

**Comment by fyrkant** [comment]
Are these two separate issues, no connection between them?

**Comment by Twois** [comment]
@fyrkant the second issue, comes if we run into the first, first comes always.

Our flow is:
- The editor hidden,
- User open the editor
- Tinymce set the content

- now we want to add focus to editor (but we cant, because we dont get the event object, what contain the editor, what we could use to set the focus on it)

the second issue means, if we add an event subscribe to editor, than auto focus dose not work.

If we dont add the event subscribe, then auto focus work if we use *ngIf instead fxShow, but in that case the caret appear at front of the text not at the end (because focus was added before the content have been set).

**Comment by fyrkant** [comment]
Seems like it has to be `handleEvent($event)`, so it seems like the readme is incorrect! Weird, I think it used to work with `$eventObj` before, maybe something changed in Angular? Anyway, try doing `handleEvent($event)` and see if that works better, I'll update the readme.

**Comment by Twois** [comment]
Yes, you are right!

**Comment by fyrkant** [comment]
Awesome! Then I can close this issue?

**Comment by Twois** [comment]
Yes!
