### ISSUE TITLE
Not work, help please.

### ISSUE THREAD

**Issue by Here21** [tinymce/tinymce-angular#41]
![image](https://user-images.githubusercontent.com/12051024/46784069-4b142a00-cd5f-11e8-83a6-2b0b36eeebfd.png)
I according the guide setup tinymce in my project, but got that.

Is something I missed?

**Comment by fyrkant** [comment]
You are not loading the skin correctly.

**Comment by rqton** [comment]
Hey, had the same issue : just take a look here : https://go.tiny.cloud/blog/angular-2-and-tinymce/ on "Getting the skin"

**Comment by Here21** [comment]
thanks bro. I got it, very helpful~ @rqton
