### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by kovaljames** [tinymce/tinymce-angular#43]
Im receiving an error `Failed to load plugin url: https://cloud.tinymce.com/stable/langs/pt_BR.js` when passing language attribute: `<editor [init]="{ language: 'pt_BR' }"> </editor>`. Is this CDN related? Is there a way to translate the editor?

**Comment by fyrkant** [comment]
Unfortunately the translations are not available on the cloud at the moment, so you'll have to [download](https://www.tiny.cloud/get-tiny/language-packages/) the translation and host it on your server and link it in with the [`language_url` setting](https://www.tiny.cloud/docs/configure/localization/#language_url).
