### ISSUE TITLE
Errors when editor shown in tabs

### ISSUE THREAD

**Issue by Gidmark** [tinymce/tinymce-angular#45]
I'm running Angular 7.0.2, tinymce 4.8.5 and @tinymce/tinymce-angular 2.3.1.

If i have a tab group control, and inside that i have an editor inside one of the tabs, i sometimes get errors. The editor shows, but the content is hidden and locked.

`ERROR TypeError: "elm is undefined"
	aria http://localhost:8333/dist/lib/tinymce//themes/modern/theme.js:2454:11
	postRender http://localhost:8333/dist/lib/tinymce//themes/modern/theme.js:2581:11
	postRender http://localhost:8333/dist/lib/tinymce//themes/modern/theme.js:3990:9
	createMethod http://localhost:8333/dist/lib/tinymce/tinymce.js:25712:17
	postRender http://localhost:8333/dist/lib/tinymce//themes/modern/theme.js:8466:16
	createMethod http://localhost:8333/dist/lib/tinymce/tinymce.js:25712:17
	exec http://localhost:8333/dist/lib/tinymce//themes/modern/theme.js:1874:13
	1 http://localhost:8333/dist/lib/tinymce/tinymce.js:2113:15
	each http://localhost:8333/dist/lib/tinymce//themes/modern/theme.js:1832:9
	exec http://localhost:8333/dist/lib/tinymce//themes/modern/theme.js:1872:9
	postRender http://localhost:8333/dist/lib/tinymce//themes/modern/theme.js:3202:22
	createMethod http://localhost:8333/dist/lib/tinymce/tinymce.js:25712:17
	postRender http://localhost:8333/dist/lib/tinymce//themes/modern/theme.js:8300:16
	createMethod http://localhost:8333/dist/lib/tinymce/tinymce.js:25712:17
	exec http://localhost:8333/dist/lib/tinymce//themes/modern/theme.js:1874:13
	1 http://localhost:8333/dist/lib/tinymce/tinymce.js:2113:15
	each http://localhost:8333/dist/lib/tinymce//themes/modern/theme.js:1832:9
	exec http://localhost:8333/dist/lib/tinymce//themes/modern/theme.js:1872:9
	postRender http://localhost:8333/dist/lib/tinymce//themes/modern/theme.js:3202:22
	createMethod http://localhost:8333/dist/lib/tinymce/tinymce.js:25712:17
	exec http://localhost:8333/dist/lib/tinymce//themes/modern/theme.js:1874:13
	1 http://localhost:8333/dist/lib/tinymce/tinymce.js:2113:15
	each http://localhost:8333/dist/lib/tinymce//themes/modern/theme.js:1832:9
	exec http://localhost:8333/dist/lib/tinymce//themes/modern/theme.js:1872:9
	postRender http://localhost:8333/dist/lib/tinymce//themes/modern/theme.js:3202:22
	createMethod http://localhost:8333/dist/lib/tinymce/tinymce.js:25712:17
	renderBefore http://localhost:8333/dist/lib/tinymce//themes/modern/theme.js:2522:9
	render http://localhost:8333/dist/lib/tinymce//themes/modern/theme.js:1170:7
	renderUI http://localhost:8333/dist/lib/tinymce//themes/modern/theme.js:3921:70
	renderUI http://localhost:8333/dist/lib/tinymce//themes/modern/theme.js:4745:16
	renderFromLoadedTheme http://localhost:8333/dist/lib/tinymce/tinymce.js:23770:14
	renderThemeUi http://localhost:8333/dist/lib/tinymce/tinymce.js:23818:16
	2 http://localhost:8333/dist/lib/tinymce/tinymce.js:23835:17
	loadScripts http://localhost:8333/dist/lib/tinymce/tinymce.js:23921:13
	loadScripts http://localhost:8333/dist/lib/tinymce/tinymce.js:6726:19
	1 http://localhost:8333/dist/lib/tinymce/tinymce.js:2113:15
	loadScripts http://localhost:8333/dist/lib/tinymce/tinymce.js:6723:13
	loadScripts http://localhost:8333/dist/lib/tinymce/tinymce.js:6736:9
	loadQueue http://localhost:8333/dist/lib/tinymce/tinymce.js:6673:9
	loadScripts http://localhost:8333/dist/lib/tinymce/tinymce.js:23919:9
	waitFor http://localhost:8333/dist/lib/tinymce/tinymce.js:6847:11
	loadTheme http://localhost:8333/dist/lib/tinymce/tinymce.js:23875:11
	loadScripts http://localhost:8333/dist/lib/tinymce/tinymce.js:6726:19
	1 http://localhost:8333/dist/lib/tinymce/tinymce.js:2113:15
	loadScripts http://localhost:8333/dist/lib/tinymce/tinymce.js:6723:13
	loadScripts http://localhost:8333/dist/lib/tinymce/tinymce.js:6736:9
	loadQueue http://localhost:8333/dist/lib/tinymce/tinymce.js:6673:9
	loadTheme http://localhost:8333/dist/lib/tinymce/tinymce.js:23874:9
	loadScripts http://localhost:8333/dist/lib/tinymce/tinymce.js:23916:7
	render http://localhost:8333/dist/lib/tinymce/tinymce.js:24008:7
	render http://localhost:8333/dist/lib/tinymce/tinymce.js:24566:9
	createEditor http://localhost:8333/dist/lib/tinymce/tinymce.js:25333:13
	initEditors http://localhost:8333/dist/lib/tinymce/tinymce.js:25363:17
	1 http://localhost:8333/dist/lib/tinymce/tinymce.js:2113:15
	initEditors http://localhost:8333/dist/lib/tinymce/tinymce.js:25359:13
	bind http://localhost:8333/dist/lib/tinymce/tinymce.js:963:15
	bind http://localhost:8333/dist/lib/tinymce/tinymce.js:6442:16
	init http://localhost:8333/dist/lib/tinymce/tinymce.js:25369:9
	initialise http://localhost:8333/dist/lib/tinymce-angular.js:1:9042
	invoke http://localhost:8333/dist/lib/zone.js:388:17
	run http://localhost:8333/dist/lib/zone.js:138:24
	runOutsideAngular http://localhost:8333/dist/lib/angular/core.js:14153:20
	initialise http://localhost:8333/dist/lib/tinymce-angular.js:1:8997
	ngAfterViewInit http://localhost:8333/dist/lib/tinymce-angular.js:1:7613
	callProviderLifecycles http://localhost:8333/dist/lib/angular/core.js:18964:13
	callElementProvidersLifecycles http://localhost:8333/dist/lib/angular/core.js:18938:17
	callLifecycleHooksChildrenFirst http://localhost:8333/dist/lib/angular/core.js:18928:33
	checkAndUpdateView http://localhost:8333/dist/lib/angular/core.js:19864:9
	callViewAction http://localhost:8333/dist/lib/angular/core.js:20096:25
	execComponentViewsAction http://localhost:8333/dist/lib/angular/core.js:20038:17
	checkAndUpdateView http://localhost:8333/dist/lib/angular/core.js:19861:9
	callViewAction http://localhost:8333/dist/lib/angular/core.js:20096:25
	execComponentViewsAction http://localhost:8333/dist/lib/angular/core.js:20038:17
	checkAndUpdateView http://localhost:8333/dist/lib/angular/core.js:19861:9
	callViewAction http://localhost:8333/dist/lib/angular/core.js:20096:25
	execEmbeddedViewsAction http://localhost:8333/dist/lib/angular/core.js:20059:21
	checkAndUpdateView http://localhost:8333/dist/lib/angular/core.js:19856:9
	callViewAction http://localhost:8333/dist/lib/angular/core.js:20096:25
	execEmbeddedViewsAction http://localhost:8333/dist/lib/angular/core.js:20059:21
	checkAndUpdateView http://localhost:8333/dist/lib/angular/core.js:19856:9
	callViewAction http://localhost:8333/dist/lib/angular/core.js:20096:25
	execComponentViewsAction http://localhost:8333/dist/lib/angular/core.js:20038:17
	checkAndUpdateView http://localhost:8333/dist/lib/angular/core.js:19861:9
	callViewAction http://localhost:8333/dist/lib/angular/core.js:20096:25
	execEmbeddedViewsAction http://localhost:8333/dist/lib/angular/core.js:20059:21
	checkAndUpdateView http://localhost:8333/dist/lib/angular/core.js:19856:9
	callViewAction http://localhost:8333/dist/lib/angular/core.js:20096:25
	execEmbeddedViewsAction http://localhost:8333/dist/lib/angular/core.js:20059:21
	checkAndUpdateView http://localhost:8333/dist/lib/angular/core.js:19856:9
	callViewAction http://localhost:8333/dist/lib/angular/core.js:20096:25
	execEmbeddedViewsAction http://localhost:8333/dist/lib/angular/core.js:20059:21
	checkAndUpdateView http://localhost:8333/dist/lib/angular/core.js:19856:9
	callViewAction http://localhost:8333/dist/lib/angular/core.js:20096:25
	execComponentViewsAction http://localhost:8333/dist/lib/angular/core.js:20038:17
	checkAndUpdateView http://localhost:8333/dist/lib/angular/core.js:19861:9
	callViewAction http://localhost:8333/dist/lib/angular/core.js:20096:25
	execEmbeddedViewsAction http://localhost:8333/dist/lib/angular/core.js:20059:21
	checkAndUpdateView http://localhost:8333/dist/lib/angular/core.js:19856:9
	callViewAction http://localhost:8333/dist/lib/angular/core.js:20096:25
	execComponentViewsAction http://localhost:8333/dist/lib/angular/core.js:20038:17
	checkAndUpdateView http://localhost:8333/dist/lib/angular/core.js:19861:9
	callViewAction http://localhost:8333/dist/lib/angular/core.js:20096:25
	execComponentViewsAction http://localhost:8333/dist/lib/angular/core.js:20038:17
	checkAndUpdateView http://localhost:8333/dist/lib/angular/core.js:19861:9
	callViewAction http://localhost:8333/dist/lib/angular/core.js:20096:25
	execEmbeddedViewsAction http://localhost:8333/dist/lib/angular/core.js:20059:21
	checkAndUpdateView http://localhost:8333/dist/lib/angular/core.js:19856:9
	callViewAction http://localhost:8333/dist/lib/angular/core.js:20096:25
	execComponentViewsAction http://localhost:8333/dist/lib/angular/core.js:20038:17
	checkAndUpdateView http://localhost:8333/dist/lib/angular/core.js:19861:9
	callWithDebugContext http://localhost:8333/dist/lib/angular/core.js:20749:26
	debugCheckAndUpdateView http://localhost:8333/dist/lib/angular/core.js:20427:16
	detectChanges http://localhost:8333/dist/lib/angular/core.js:18236:17
	tick http://localhost:8333/dist/lib/angular/core.js:14922:62
	tick http://localhost:8333/dist/lib/angular/core.js:14922:17
	next http://localhost:8333/dist/lib/angular/core.js:14813:103
	invoke http://localhost:8333/dist/lib/zone.js:388:17
	onInvoke http://localhost:8333/dist/lib/angular/core.js:14194:28
	invoke http://localhost:8333/dist/lib/zone.js:387:17
	run http://localhost:8333/dist/lib/zone.js:138:24
	run http://localhost:8333/dist/lib/angular/core.js:14108:20
	next http://localhost:8333/dist/lib/angular/core.js:14813:73
	schedulerFn http://localhost:8333/dist/lib/angular/core.js:10299:40
	__tryOrUnsub http://localhost:8333/dist/lib/rxjs/internal/Subscriber.js:209:13
	next http://localhost:8333/dist/lib/rxjs/internal/Subscriber.js:147:17
	_next http://localhost:8333/dist/lib/rxjs/internal/Subscriber.js:90:9
`

`	View_RichTextComponent_0
RichTextComponent.html:2:3
proxyClass
http://localhost:8333/dist/lib/angular/compiler.js:17185:24
DebugContext_.prototype.logError
http://localhost:8333/dist/lib/angular/core.js:20711:13
ErrorHandler.prototype.handleError
http://localhost:8333/dist/lib/angular/core.js:12688:17
ApplicationRef.prototype.tick/<
http://localhost:8333/dist/lib/angular/core.js:14929:67
ZoneDelegate.prototype.invoke
http://localhost:8333/dist/lib/zone.js:388:17
Zone.prototype.run
http://localhost:8333/dist/lib/zone.js:138:24
NgZone.prototype.runOutsideAngular
http://localhost:8333/dist/lib/angular/core.js:14153:20
ApplicationRef.prototype.tick
http://localhost:8333/dist/lib/angular/core.js:14929:17
next/<
http://localhost:8333/dist/lib/angular/core.js:14813:103
ZoneDelegate.prototype.invoke
http://localhost:8333/dist/lib/zone.js:388:17
onInvoke
http://localhost:8333/dist/lib/angular/core.js:14194:28
ZoneDelegate.prototype.invoke
http://localhost:8333/dist/lib/zone.js:387:17
Zone.prototype.run
http://localhost:8333/dist/lib/zone.js:138:24
NgZone.prototype.run
http://localhost:8333/dist/lib/angular/core.js:14108:20
next
http://localhost:8333/dist/lib/angular/core.js:14813:73
EventEmitter.prototype.subscribe/schedulerFn<
http://localhost:8333/dist/lib/angular/core.js:10299:40
SafeSubscriber.prototype.__tryOrUnsub
http://localhost:8333/dist/lib/rxjs/internal/Subscriber.js:209:13
SafeSubscriber.prototype.next
http://localhost:8333/dist/lib/rxjs/internal/Subscriber.js:147:17
Subscriber.prototype._next
http://localhost:8333/dist/lib/rxjs/internal/Subscriber.js:90:9
Subscriber.prototype.next
http://localhost:8333/dist/lib/rxjs/internal/Subscriber.js:67:13
Subject.prototype.next
http://localhost:8333/dist/lib/rxjs/internal/Subject.js:60:25
EventEmitter.prototype.emit
http://localhost:8333/dist/lib/angular/core.js:10283:58
checkStable
http://localhost:8333/dist/lib/angular/core.js:14163:17
onHasTask
http://localhost:8333/dist/lib/angular/core.js:14207:25
ZoneDelegate.prototype.hasTask
http://localhost:8333/dist/lib/zone.js:441:21
ZoneDelegate.prototype._updateTaskCount
http://localhost:8333/dist/lib/zone.js:461:17
Zone.prototype._updateTaskCount
http://localhost:8333/dist/lib/zone.js:285:34
Zone.prototype.runTask
http://localhost:8333/dist/lib/zone.js:205:25
drainMicroTaskQueue
http://localhost:8333/dist/lib/zone.js:595:25
ZoneTask.invokeTask
http://localhost:8333/dist/lib/zone.js:500:21
ZoneTask/this.invoke
http://localhost:8333/dist/lib/zone.js:485:28
timer
http://localhost:8333/dist/lib/zone.js:2054:17
`

**Comment by fyrkant** [comment]
I think this is connected to #9 and unfortunately not something that can be fixed easily.

**Comment by Gidmark** [comment]
I worked around it by loading the tabs asynchronously, but o well

**Comment by fyrkant** [comment]
Ok, that's good to hear.
