### ISSUE TITLE
Using `fixed_toolbar_container` with tinymce-angular

### ISSUE THREAD

**Issue by mmccoy** [tinymce/tinymce-angular#5]
I'm trying to utilize this configuration option, but i get theres an error in the console:

```
TypeError: Cannot read property 'setAttribute' of undefined
```

I suspect its something to do with the way angular renders templates.  I can confirm the element is in the dom (via devtools inspection), but at the time of init, maybe its not?

Any help is appreciated.

**Comment by fyrkant** [comment]
Hmm, yeah this might be hard to get to work... I'll take some time and look into it today!

**Comment by fyrkant** [comment]
Quickly testing it now it seems to work without problems for me, can you share some more code from you project so maybe I can reproduce it?

**Comment by mmccoy** [comment]
Thanks for looking at it!

I don't exactly know where I went wrong, but I started from scratch with a local instance and it worked.. the previous attempt was on stackblitz, perhaps that factored in?

**Comment by fyrkant** [comment]
Yeah could have been something with stackblitz that factored in, good that you got it working!
