### ISSUE TITLE
Formgroup valuechanges only fired once

### ISSUE THREAD

**Issue by joensindholt** [tinymce/tinymce-angular#54]
When using the editor with reactive forms and subscribing to `valueChanges` with `updateOn: 'blur'`, values are only emitted on first blur.

Expectation: `valueChanges` should emit on all blurs just as normal text inputs.

I've made reproducable example here: [https://stackblitz.com/edit/angular-mbyihs](https://stackblitz.com/edit/angular-mbyihs)

**Comment by tsiegleauq** [comment]
without `updateOn` changes are fired too often btw. Calling `form.patchValue` with the same content as the form had before will be detected as a valueChange.

**Comment by fyrkant** [comment]
I'm unsure how these things work, I don't really know what reactive forms are really, so I don't know how to fix this... Help wanted!

**Comment by joensindholt** [comment]
I looked in to the issue. The problem is in:
https://github.com/tinymce/tinymce-angular/blob/90b7c602a6b5f5b1309ccddad083f4210bce1f84/tinymce-angular-component/src/editor/editor.component.ts#L156

The `onTouchedCallback` is only invoked once. This should be on all blur's according to https://angular.io/api/forms/ControlValueAccessor#registerOnTouched-usage-notes

I will be happy to do a PR if needed. Let me know.

**Comment by fyrkant** [comment]
A PR would be great!

**Comment by joensindholt** [comment]
Alright...I'll look into it ASAP
