### ISSUE TITLE
Multiple tinymce on a single page

### ISSUE THREAD

**Issue by iamdue** [tinymce/tinymce-angular#57]
When I have multiple tinymce editor on a single page the library connects cloud as many as editor i have on the page. (example: 3 editor element means 3 connections to cloud). How can I prevent this?

**Comment by fyrkant** [comment]
It only downloads a small css file for each editor, the editor javascript should only be downloaded once per page.

**Comment by fyrkant** [comment]
And the css has to be loaded once for every editor because it is loaded from inside of an iframe.
