### ISSUE TITLE
Angular 7 / Ionic 4 - Keyboard won't close on iOS

### ISSUE THREAD

**Issue by Jahrenski** [tinymce/tinymce-angular#63]
Hi, I wonder if you have a solution for this breaking bug in iOS using tinyMCE in an Angular 7 / Ionic 4 application.

I have a tinyMCE editor inside a modal window to write messages from.
On iOS only, if you focus on the editor, the keyboard opens. So far so good.
Then if you close the modal window (this removes the editor from the DOM), then the keyboard stays open. 

The real problem here is that whatever you try, you cannot dismiss the keyboard afterwards until you close the application completely. The keyboard seems to dismiss but will reopen indefinitely.

Anyone else has noticed this?

**Comment by fyrkant** [comment]
Are you using the mobile editor theme?

**Comment by Jahrenski** [comment]
I am not.
These are my configs:

`
      anchor_bottom:                false, 
      anchor_top:                   false,
      autoresize_bottom_margin:     10,
      autoresize_min_height:        40,
      branding:                     false, 
      language:                     culture, 
      inline:                       true,
      fixed_toolbar_container:      ".tiny-mce-toolbar",
      menubar:                      false, 
      statusbar:                    false, 
      default_link_target:          '_blank', 
      link_assume_external_targets: true, 
      target_list:                  false, 
      link_title:                   false,
      skin_url:                     'assets/tinymce/skins/lightgray'
`

**Comment by AdwayAtHealthlevel** [comment]
I am facing the same issue. Our end-users don't use tinymce much on Mobile, so it has not become an issue (yet).

**Comment by SimonFc** [comment]
@Jahrenski @AdwayAtHealthlevel  Is this still an issue? If so, see if you can reproduce the issue on [codesandbox](https://codesandbox.io/s/6zlmmkkk1n?fontsize=14)

**Comment by Jahrenski** [comment]
I haven't updated this for a long time but this is due to an interaction between Ionic and Tiny's editor. 
The fix back then was to use the no-blur attribute on the editor along with some hack when the component is about to be destroyed (ionViewWillLeave), it will focus on an input on the page so it dismisses correctly.

I will mark this issue as closed.

**Comment by jaganreddy314** [comment]
Make sure you keep tinymce editor out of <form> tag

**Comment by mikkimichaelis** [comment]
Hi, I’m experiencing this same issue on iOS, Ionic 6.5.5, Angular 15.1.1, TinyMCE/Angular 7.0.0.  I’ll try to implement the above fix reported by @Jahrenski.
