### ISSUE TITLE
How to set the Height property?

### ISSUE THREAD

**Issue by bhaidar** [tinymce/tinymce-angular#69]
Hi,
Is there I can set the `Height` for the editor?

The TinyMCE editor accepts `height` property in the init() function.

Thanks

**Comment by fyrkant** [comment]
You can use the `[init]` input and send in a  configuration object with height set.

**Comment by bhaidar** [comment]
@fyrkant This is not working! Have you tried it on your side?

**Comment by fyrkant** [comment]
This is working for me.
```ts
<editor [init]="{height: 500}"></editor>
```

**Comment by bhaidar** [comment]
I tried that and it is not working!

**Comment by bhaidar** [comment]
This is in brief what I have:

````
const defaultConfig = {
  ...
  inline: true,
  height: 300,
};

@Component({
  template: `
    <editor
      [formControl]="formControl"
      [formlyAttributes]="field"
      [init]="config"
      [initialValue]="formControl.value || to.initialValue"
    >
    </editor>
  `,
})
export class TinyMceTypeComponent extends FieldType implements OnInit {
  public config = {};

  ngOnInit() {
    super.ngOnInit();
    this.config = { ...defaultConfig };
  }
}
````

**Comment by fyrkant** [comment]
I suspect the ngOnInit is too late so the editor has aldready initialised when you set the config? The editor only reads the config when it initialises, it doesn't change reactively to changes in the config.

**Comment by bhaidar** [comment]
How can I fix that :-) ?

**Comment by bhaidar** [comment]
BTW, I debugged the `tinymce-angular` component and the value of `finalInit` is:
````
...
height: 300
setup: ƒ (editor)
...
```

**Comment by bhaidar** [comment]
Also, I noticed that the `tinymce-angular` component calls `initialise()` inside `AfterViewInit` so it should catch the values set in `OnInit`, no?

**Comment by fyrkant** [comment]
Try putting the height setting in the config property directly and not after init and see if it works.

**Comment by bhaidar** [comment]
Also it doesn't work! I tried that. This is what I have above if you notice the sample code.

**Comment by fyrkant** [comment]
No in the code sample above you set the config values in ngOnInit?

**Comment by bhaidar** [comment]
Correct! Something like this would work?
````
export class TinyMceTypeComponent extends FieldType implements OnInit {
  public config = { ...defaultConfig };

  ngOnInit() {
    super.ngOnInit();
  }
}
```

Also, still height is not taking effect.

**Comment by fyrkant** [comment]
Yes that should work, and does work in my testing. Maybe there's some css in your page changing the editor height?

**Comment by bhaidar** [comment]
I don't see any css rules overriding the height!

**Comment by fyrkant** [comment]
Can you create a simple app where I can reproduce this problem?

**Comment by bhaidar** [comment]
Great! Thanks a lot for your time.

**Comment by kailynnelson** [comment]
> @fyrkant
> It seems when `inline=true` the height has no effect! When I set `inline=false` the height is now taking effect.

Where are you setting this inline property?

**Comment by jscasca** [comment]
In the editor component.
```
<editor
  [inline]="true"
></editor>
```

You can find the docs here: https://www.tiny.cloud/docs/integrations/angular/#exampleinline

**Comment by kailynnelson** [comment]
> In the editor component.
> 
> ```
> <editor
>   [inline]="true"
> ></editor>
> ```
> 
> You can find the docs here: https://www.tiny.cloud/docs/integrations/angular/#exampleinline

I had looked at the documentation already. Our developer set it up differently. We solved it by extending ViewOnInit and setting the confit then.
