### ISSUE TITLE
tinymce destory issue

### ISSUE THREAD

**Issue by jecyhw** [tinymce/tinymce-angular#7]
i used tinymce-angular <editor> component in tow pages, when i click route one page, then quickly click route to another page, some error happened. look like the photo.  how to solve it, thank you.
![image](https://user-images.githubusercontent.com/10094084/38254596-4390304e-378c-11e8-8103-a567ab277d5a.png)

**Comment by fyrkant** [comment]
Can you create a app reproducing this and share the code?

**Comment by jecyhw** [comment]
App demo: https://stackblitz.com/edit/angular-wk7xun.
App has tow pages, every page contains <editor> component. This issue only happened when click one page link, but this page's tinymce.js doesn't complete loaded , then click another page link. The console will show the error.  There is no problem when tinymce.js firstly loaded.

**Comment by fyrkant** [comment]
I don't think this is still an issue in the version so I'm closing this, but if anyone is still seeing this leave a comment or open a new issue.
