### ISSUE TITLE
how to change the language in tinymce-angular

### ISSUE THREAD

**Issue by diankourenxia** [tinymce/tinymce-angular#72]
sorry,I'm puzzled about it

**Comment by SimonFc** [comment]
Please refer to this page: https://www.tiny.cloud/docs/configure/localization/#language
"tinymce-angular" is a wrapper so pass any settings you wish to have to the init param.

**Comment by diankourenxia** [comment]
thx for your help.I set the language, and get the message Failed to load the plugin url: https://cloud.tinymce.com/5/langs/zh_CN.js because I am in China, connecting the cloud can be slow or even fail, and my key authentication is very slow, often wait for a few seconds or even minutes, can I use offline

**Comment by gcrtime** [comment]
in react?  how?

**Comment by SimonFc** [comment]
@gcrtime Demo for React https://codesandbox.io/s/kr24wmk55?fontsize=14

@diankourenxia You may use the language_url if you want to retrieve the language packs from a location other than the default one(i.e. self-hosted)

**Comment by gcrtime** [comment]
@SimonFc Thanks! I can't open this website. Maybe it's domain name restriction.My project is in typeScript environment. I used a CDN address, but it's only half effective. I don't know how to put this language file in TS environment. I tried a lot of methods, but none of them worked.

**Comment by SimonFc** [comment]
Hmm it's difficult for me to say since this is a question that's specific to your project, but basically what you need to do is to be able to serve these language files as assets through whatever server you're using so that Tiny would be able to load it.

When you say that you use a CDN, do you mean that you're loading Tiny through a CDN? (That would probably mean that you're using Tiny Cloud)

**Comment by gcrtime** [comment]
@SimonFc  Emmmmmmm········I actually know how you use it.Maybe my project is so special.In ts, I use 'npm-@tinymce/tinymce-react',There is no'/lang/'path under this project.So I use 'language_url:
              "https://cdn.shoplazza.com/oss/operation/e304ad027acebf37a178649bb976fc6e.js",'but it's only half effective.=.==.=So  sad

**Comment by gcrtime** [comment]
@diankourenxia 你好，你在angular环境下的那个url https://cloud.tinymce.com/5/langs/zh_CN.js如果首次使用，这个插件是不生效的，有解决办法么或者更好的使用方式，我是在react+ts环境下的

**Comment by SimonFc** [comment]
What do you mean with "it's only half effective"? Either it works or it doesn't?

**Comment by gcrtime** [comment]
@SimonFc NO，
![image](https://user-images.githubusercontent.com/37494683/57680088-65004d00-765f-11e9-8557-af14ae08a20c.png)
like this;One place has changed, but the other has not changed.

**Comment by SimonFc** [comment]
Is there any other place that hasn't been updated? Font names aren't anything we have translations for since they're names. You could update the [font_formats](https://www.tiny.cloud/docs/configure/editor-appearance/#font_formats) option manually though if you have any custom strings that you would like to use so that could solve this specific issue

**Comment by gcrtime** [comment]
@SimonFc 
![image](https://user-images.githubusercontent.com/37494683/57681983-65024c00-7663-11e9-994f-81083cf4cce0.png)like this?I uesd,I just hope his name will be changed into Chinese.
code：
![image](https://user-images.githubusercontent.com/37494683/57682122-a72b8d80-7663-11e9-98a4-d58cb4086aa6.png)

**Comment by SimonFc** [comment]
@gcrtime  Actually the word "System Font" itself is something that should be translated but isn't in your case, you're right about that. The language pack you're using seems to be outdated though. The latest Chinese(China/Taiwan) language pack [here](https://www.tiny.cloud/get-tiny/language-packages/) do have translations for that string

**Comment by gcrtime** [comment]
@SimonFc My Language Pack is the latest。But it do not work ,so l ues CDN address,Is a language package for other sites cited，so sad

**Comment by SimonFc** [comment]
This is my result from using the zh_CN language pack from [here](https://www.tiny.cloud/get-tiny/language-packages/)
![Screenshot from 2019-05-14 10-27-49](https://user-images.githubusercontent.com/39832182/57682924-06bd7500-7633-11e9-9ab8-721d118fd6fe.png)

**Comment by gcrtime** [comment]
@SimonFc  I know.but useless，It's not going to solve my problem.

**Comment by versedi** [comment]
@SimonFc I'm confused, all of the issues are closed, also for react but there's not a single response if it's actually doable without having to include the language separately.

I mean it's 2019, people use Webpack, rollup - this is a VERY basic option that should be documented for all use cases.

**Comment by SimonFc** [comment]
You can absolutely make a bundle of all the js. Some [info](https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/). The language packs aren't available on npmjs but you can [download](https://www.tiny.cloud/get-tiny/language-packages/) them and include them in your bundle.
```
import tinymce from 'tinymce';
import 'tinymce/themes/silver';
import 'path/to/ar.js';

// Any plugins you want to use has to be imported
import 'tinymce/plugins/paste';
import 'tinymce/plugins/link';
```
Does that answer your question? Or were you hopping that there would be a single import that included every single plugin, language pack etc. that tinymce provides? (Would result in a very large bundle)

**Comment by versedi** [comment]
It partially does answer my question, though I gotta say requiring loaders and lots of configuration to the bundler isn't a great developer experience. 

Just for tinymce I'll have to add around 30-40 lines to my webpack configuration.

Honestly I'd expect the language packs to be separate packages that you can download via npm and import in your script. Same goes for skins and plugins. 

Thank you for the response and have a great weekend!

**Comment by SimonFc** [comment]
Yeah that's a reasonable expectation, there has been some discussions in the past about publishing the community language packs through more channels. (I'll forward your request) The plugins and skins are already available in the 'tinymce' package under 'tinymce/skins' and 'tinymce/plugins'.

About the configuration - I understand what you mean but it's partly because we want to lean towards an "opt-in" approach and make everything very configurable. (But of course, there're both advantages and drawbacks to that)

Have a great weekend you too!

**Comment by angry-bread** [comment]
@gcrtime 老哥有解决吗，我也碰到了
