### ISSUE TITLE
Change editor config after component is initliazed

### ISSUE THREAD

**Issue by charleshimmer** [tinymce/tinymce-angular#74]
I know you can pass in the init config, but is there a way to change the editor config after it's been initialized? I have a situation where I need to hide the toolbar depending on on user events.

**Comment by charleshimmer** [comment]
Reading the source code I wonder if I need to use ViewChild to get the instance of the EditorComponent and use the `writeValue` and `registerOnChange` methods to accomplish what I need.

**Comment by fyrkant** [comment]
No I'm afraid that's not possible due to how Tinymce works.
