### ISSUE TITLE
the context from ngModel lose many class

### ISSUE THREAD

**Issue by diankourenxia** [tinymce/tinymce-angular#75]
```
1.<editor id="edit" class="editor-part" [init]=editParam [(ngModel)]="editData.content"></editor>
2.<div id="show" class="editor-show" [innerHTML]="editData.content"></div>
```
the #show is different from #edit
the editData.content has lose so many class,how i get the full content in editor

example:
insert a table:
the resource is
```
<table style="border-collapse: collapse; width: 100%;" border="1">
<tbody>
<tr>
<td style="width: 100%;">&nbsp;</td>
</tr>
</tbody>
</table>
```
the content is
```
<table border="1">
<tbody>
<tr>
<td>&nbsp;</td>
</tr>
</tbody>
</table>
```

**Comment by SimonFc** [comment]
If I understand your problem correctly it might be due to Angular sanitizing the content before inserting it into the DOM. Does this solve your issue?
https://angular.io/guide/security#sanitization-and-security-contexts

**Comment by diankourenxia** [comment]
3q very much, I use sanitizer.bypassSecurityTrustHtml and it works well

**Comment by diankourenxia** [comment]
> If I understand your problem correctly it might be due to Angular sanitizing the content before inserting it into the DOM. Does this solve your issue?
> https://angular.io/guide/security#sanitization-and-security-contexts
