### ISSUE TITLE
adding assets to angular.json

### ISSUE THREAD

**Issue by ashgibson** [tinymce/tinymce-angular#77]
Just a suggestion for angular integration. Rather than copying assets to the src directory as per documentation, instead add this to angular.json.

Under projects > architect > build

```
"assets": [
    ... other assets
    { "glob": "**/*", "input": "./node_modules/tinymce/skins", "output": "/skins/" },
    { "glob": "**/*", "input": "./node_modules/tinymce/plugins", "output": "/plugins/" }
],
"scripts": [
    ... other scripts
    "node_modules/tinymce/tinymce.js",
    "node_modules/tinymce/themes/modern/theme.js"
]
```

**Comment by diankourenxia** [comment]
"node_modules/tinymce/themes/modern/theme.js"
]
in my package the directory is mobile rather than modern
is there any thing wrong?

**Comment by diankourenxia** [comment]
we also need add css to the styles
```
 "styles": [
                            "node_modules/tinymce/skins/ui/oxide/skin.min.css",
                            "node_modules/tinymce/skins/ui/oxide/content.min.css",
                            "node_modules/tinymce/skins/content/default/content.css",
                            "src/assets/styles/prism.css",
                            "src/styles.scss"
                        ],
```
or it wont work

**Comment by zifeiyuSun** [comment]
> we also need add css to the styles
> 
> ```
>  "styles": [
>                             "node_modules/tinymce/skins/ui/oxide/skin.min.css",
>                             "node_modules/tinymce/skins/ui/oxide/content.min.css",
>                             "node_modules/tinymce/skins/content/default/content.css",
>                             "src/assets/styles/prism.css",
>                             "src/styles.scss"
>                         ],
> ```
> 
> or it wont work

me too, so what happend? Who knows?

**Comment by maxtacco** [comment]
This setup worked for me for TinyMCE 5
1. Add TinyMCE assets and scripts to angular.json as explained above:  
```json
            "assets": [
              "src/favicon.ico",
              "src/assets",
              ...
              {
                "glob": "**/*",
                "input": "./node_modules/tinymce/plugins",
                "output": "/assets/tinymce/plugins"
              },
              {
                "glob": "**/*",
                "input": "node_modules/tinymce/skins",
                "output": "/assets/tinymce/skins"
              },
              {
                "glob": "**/*",
                "input": "./node_modules/tinymce/themes",
                "output": "/assets/tinymce/themes"
              }
            ],
            "styles": [
             ...
            ],
            "scripts": [
              "node_modules/tinymce/tinymce.min.js"
            ]
```

2. Add TinyMCE pre-init in index.html
```html
<head>
 ...
  <script>
    window.tinyMCEPreInit = {
      base: '/assets/tinymce',
      suffix: '.min'
    }
  </script>
</head>
```

Hope this helps.

**Comment by SimonFc** [comment]
@ashgibson I agree that the readme should describe loading TinyMCE in a similar fashion as you described. I've updated the readme to include this. The great benefit of doing this, instead of including everything as a global script, is of course simplicity but also it matters to bundle size. Tiny can load everything it requires on initialization instead of having everything(plugins, theme) included in the initial bundle.

@maxtacco Great to see what you have figured out! I've updated the readme to include something similar although I've opted to use `overrideDefaults` on the global `tinymce` object instead of `tinyMCEPreInit` since it could be considered a legacy thing. The result is the same though.

**Comment by maxtacco** [comment]
@SimonFc The only problem I see with your approach is that it is not that easy to determine where to place the call `window.tinyMCE. overrideDefaults ` in Angular's index.html. It has to execute right after tinymce script is loaded but script tags are generated dynamically in Angular, so it requires listening for "document ready" event.

**Comment by SimonFc** [comment]
@maxtacco  I placed the `overrideDefaults` call in the constructor of my root component when trying it out which I suppose isn't that clean either. It feels a bit fractured but I wanted to avoid recommending something which Tiny is moving away from and might drop. I don't think there's an obvious clean solution here (Other than using Tiny Cloud, but then this is about self-hosting)

Let me know if you have any ideas for improvements here

**Comment by maxtacco** [comment]
@SimonFc Thank you, I can't think of a better / easier way for now.

**Comment by filipefreitas82** [comment]
[Here](https://www.tiny.cloud/docs/tinymce/6/angular-pm/), the documentation still says to copy all the files like so:
```
"assets": [
  { "glob": "**/*", "input": "node_modules/tinymce", "output": "/tinymce/" }
]
```
The way mentioned in this issue makes more sense as it decreases bundle size for one.
