### ISSUE TITLE
selector don't work with several textarea

### ISSUE THREAD

**Issue by trdmitry** [tinymce/tinymce-angular#82]
teaxtarea doesn't hide when it's two on page, example: https://stackblitz.com/edit/angular7tinymce
![image](https://user-images.githubusercontent.com/3643368/56861744-8cdb8980-69ac-11e9-8045-fd55e00c7ebd.png)

Work correct in html + js
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="node_modules/tinymce/tinymce.js"></script>
    <script>tinymce.init({selector:'textarea#t2'});</script>
</head>
<body>

<textarea class="mydiv" id="t1">Table1</textarea>
<textarea class="mydiv" id="t2">Table2</textarea>

</body>
</html>
```
![image](https://user-images.githubusercontent.com/3643368/56861763-d2985200-69ac-11e9-85b3-a0b80522ba20.png)

**Comment by SimonFc** [comment]
Hi! I don't think it should be possible to use a selector at all. The tinymce-angular wrapper takes care of the creation of a target element since the point of frameworks like angular is to have them encapsulated and intuitive. Perhaps a warning should be shown if a selector is being used.
