### ISSUE TITLE
how to change the language in tinymce-react and typescript

### ISSUE THREAD

**Issue by gcrtime** [tinymce/tinymce-angular#84]
My project is a ‘react + TS’ project.Now.I want to use tinymce-react,But how to change the language.I can't put my Chinese package in the project，because  no'/lang/'path，No path is possible.So I use a cdn address,but it's only half effective,so sad,who can resolve this problem?
MAYDAY

**Comment by SimonFc** [comment]
I'm closing this one since we already had a thread going on over here: https://github.com/tinymce/tinymce-angular/issues/72
Also, tinymce-react issues should be opened over [here](https://github.com/tinymce/tinymce-react/issues)
