### ISSUE TITLE
Update to angular 8 in package

### ISSUE THREAD

**Issue by jpike88** [tinymce/tinymce-angular#91]
```@tinymce/tinymce-angular@3.0.1 requires a peer of @angular/core@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.```

**Comment by jpike88** [comment]
@SimonFc poke... this is probably a good one to knock some sooner rather than later

**Comment by SimonFc** [comment]
Hi, this is fixed in @tinymce/tinymce-angular@3.1.0. Thanks for reporting the issue.
