### ISSUE TITLE
How to set the line spacing between line 

### ISSUE THREAD

**Issue by uamrit** [tinymce/tinymce-angular#94]
How to set the line spacing between line like word
![image](https://user-images.githubusercontent.com/40016378/59353884-92fdad80-8d41-11e9-8832-8e2bc798588a.png)

**Comment by SimonFc** [comment]
Hi @uamrit, this would have to be done by setting custom content css with [content_css](https://www.tiny.cloud/docs/configure/content-appearance/#content_css) or [content_style](https://www.tiny.cloud/docs/configure/content-appearance/#content_style). It's up to you what css you decide to use. `line-height`, margin etc. Hope this answer your question!
